---
# unifi protect backup
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi-protect-backup
  namespace: knick-knacks
spec:
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: ./Helm/apps/unifi-protect-backup
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
---
# semaphore ui
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: semaphore
  namespace: knick-knacks
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: ansible-semaphore
      version: 12.11.6
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: cloudhippie
        namespace: flux-system
  values:
    fullnameOverride: semaphore
    image:
      repository: semaphoreui/semaphore
      tag: v2.13.2
    admin:
      create: true
      existingSecret: "semaphore-secrets"
      emailKey: "adminemail"
      fullnameKey: "adminfullname"
      usernameKey: "adminusername"
      passwordKey: "adminpassword"
    database:
      type: "mysql"
      host: "mariadb.database.svc.cluster.local"
      port: "3306"
      name: "semaphore"
      usernameFromSecret: false
      username: "semaphore"
      existingSecret: "semaphore-secrets"
      passwordKey: "dbpassword"
    ingress:
      enabled: true
      className: internal-nginx
      hosts:
        - host: semaphore.k8s.hyde.services
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - semaphore.k8s.hyde.services
          secretName: wildcard.hyde.services
    persistence:
      enabled: true
      size: "64Mi"
---
# nginx
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: knick-knacks
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: nginx
      version: 19.0.3
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    staticSitePVC: nginx-static-site-pvc
    ingress:
      enabled: true
      ingressClassName: external-nginx
      hostname: hyde.services
      tls: true
      extraTls:
        - hosts:
            - hyde.services
          secretName: wildcard.hyde.services
    updateStrategy:
      type: Recreate
      rollingUpdate:
