---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi-protect-backup
  namespace: knick-knacks
spec:
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: ./Helm/apps/unifi-protect-backup
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teslacamplayer
  namespace: knick-knacks
spec:
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: ./Helm/apps/teslacamplayer
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
