apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: knick-knacks
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: nginx
      version: 20.1.0
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    staticSitePVC: nginx-static-site-pvc
    ingress:
      enabled: true
      ingressClassName: external-nginx
      hostname: &host hyde.services
      tls: true
      extraTls:
        - hosts:
            - *host
          secretName: wildcard.hyde.services
    updateStrategy:
      type: Recreate
      rollingUpdate:
    service:
      type: ClusterIP
    podAnnotations:
      backup.velero.io/backup-volumes: staticsite
