apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-static-site-pvc
  namespace: knick-knacks
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 128Mi