# phpMyAdmin⁠
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: database-oci
  labels:
    app.kubernetes.io/instance: phpmyadmin
    app.kubernetes.io/name: phpmyadmin
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: phpmyadmin
      app.kubernetes.io/name: phpmyadmin
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: phpmyadmin
        app.kubernetes.io/name: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin:5.2.1
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          env:
            - name: PMA_HOST
              value: mariadb
            - name: PMA_PORT
              value: "3306"
            - name: UPLOAD_LIMIT
              value: "128M"
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 30
            timeoutSeconds: 2
            tcpSocket:
              port: 80
          startupProbe:
            failureThreshold: 10
            timeoutSeconds: 2
            tcpSocket:
              port: 80
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: database-oci
spec:
  selector:
    app.kubernetes.io/instance: phpmyadmin
    app.kubernetes.io/name: phpmyadmin
  ports:
    - name: phpmyadmin
      protocol: TCP
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phpmyadmin
  namespace: database-oci
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "128m"
spec:
  ingressClassName: internal-nginx
  tls:
    - hosts:
        - "*.oci.hyde.services"
      secretName: wildcard.hyde.services
  rules:
    - host: phpmyadmin.oci.hyde.services
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: phpmyadmin
                port:
                  number: 80
---
# phpPgAdmin
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phppgadmin
  namespace: database-oci
  labels:
    app.kubernetes.io/instance: phppgadmin
    app.kubernetes.io/name: phppgadmin
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: phppgadmin
      app.kubernetes.io/name: phppgadmin
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: phppgadmin
        app.kubernetes.io/name: phppgadmin
    spec:
      containers:
        - name: phppgadmin
          image: snimshchikov/phppgadmin:latest # no other tags 🤨
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          env:
            - name: PPA_SERVER_DESCS
              value: "postgresql;;pgvectors"
            - name: PPA_SERVER_HOSTS
              value: "postgresql.database-oci.svc.cluster.local;;pgvectors.database-oci.svc.cluster.local"
            - name: PPA_SERVER_PORTS
              value: "5432;;5432"
            - name: PPA_SERVER_SSL_MODES
              value: "disable;;disable"
            - name: PPA_EXTRA_LOGIN_SECURITY
              value: "false"
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 30
            timeoutSeconds: 2
            tcpSocket:
              port: 80
          startupProbe:
            failureThreshold: 10
            timeoutSeconds: 2
            tcpSocket:
              port: 80
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: phppgadmin
  namespace: database-oci
spec:
  selector:
    app.kubernetes.io/instance: phppgadmin
    app.kubernetes.io/name: phppgadmin
  ports:
    - name: phppgadmin
      protocol: TCP
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phppgadmin
  namespace: database-oci
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "128m"
spec:
  ingressClassName: internal-nginx
  tls:
    - hosts:
        - "*.oci.hyde.services"
      secretName: wildcard.hyde.services
  rules:
    - host: phppgadmin.oci.hyde.services
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: phppgadmin
                port:
                  number: 80
