apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
  namespace: wordpress
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: wordpress
      version: 24.2.3
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    image:
      repository: bitnami/wordpress
      tag: 6.8.1-debian-12-r0
    mariadb:
      enabled: false
    memcached:
      enabled: false
    externalCache:
      host: memcached.wordpress.svc.cluster.local
      port: 11211
    podAnnotations:
      backup.velero.io/backup-volumes: wordpress-data

  valuesFrom:
    - kind: Secret
      name: wordpress-values
