apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
  namespace: wordpress
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: wordpress
      version: 24.2.8
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    image:
      repository: bitnami/wordpress
      tag: 6.8.1-debian-12-r5
    mariadb:
      enabled: false
    memcached:
      enabled: false
    externalCache:
      host: memcached.wordpress.svc.cluster.local
      port: 11211
    podAnnotations:
      backup.velero.io/backup-volumes: wordpress-data
    apacheConfiguration: |
      ServerRoot "/opt/bitnami/apache"
      Listen 8080

      # Load core modules
      LoadModule mpm_prefork_module      modules/mod_mpm_prefork.so
      LoadModule unixd_module            modules/mod_unixd.so
      LoadModule log_config_module       modules/mod_log_config.so
      LoadModule env_module              modules/mod_env.so
      LoadModule headers_module          modules/mod_headers.so
      LoadModule setenvif_module         modules/mod_setenvif.so
      LoadModule mime_module             modules/mod_mime.so
      LoadModule dir_module              modules/mod_dir.so
      LoadModule alias_module            modules/mod_alias.so
      LoadModule php_module              modules/libphp.so
      LoadModule rewrite_module          modules/mod_rewrite.so
      LoadModule status_module           modules/mod_status.so
      LoadModule autoindex_module        modules/mod_autoindex.so
      LoadModule negotiation_module      modules/mod_negotiation.so
      LoadModule ssl_module              modules/mod_ssl.so
      LoadModule remoteip_module         modules/mod_remoteip.so
      LoadModule access_compat_module    modules/mod_access_compat.so
      LoadModule auth_basic_module       modules/mod_auth_basic.so
      LoadModule authn_core_module       modules/mod_authn_core.so
      LoadModule authn_file_module       modules/mod_authn_file.so
      LoadModule authz_core_module       modules/mod_authz_core.so
      LoadModule authz_user_module       modules/mod_authz_user.so
      LoadModule authz_host_module       modules/mod_authz_host.so
      LoadModule authz_groupfile_module  modules/mod_authz_groupfile.so
      LoadModule deflate_module          modules/mod_deflate.so
      LoadModule socache_shmcb_module    modules/mod_socache_shmcb.so
      LoadModule version_module          modules/mod_version.so
      LoadModule filter_module           modules/mod_filter.so
      LoadModule reqtimeout_module       modules/mod_reqtimeout.so
      LoadModule proxy_module            modules/mod_proxy.so
      LoadModule proxy_connect_module    modules/mod_proxy_connect.so
      LoadModule proxy_ftp_module        modules/mod_proxy_ftp.so
      LoadModule proxy_http_module       modules/mod_proxy_http.so
      LoadModule proxy_fcgi_module       modules/mod_proxy_fcgi.so
      LoadModule proxy_ajp_module        modules/mod_proxy_ajp.so
      LoadModule proxy_balancer_module   modules/mod_proxy_balancer.so
      LoadModule slotmem_shm_module      modules/mod_slotmem_shm.so

      <IfModule unixd_module>
        User daemon
        Group daemon
      </IfModule>

      ServerAdmin you@example.com
      ServerName www.example.com:8080

      # Root directory access
      <Directory />
        AllowOverride none
        Require all denied
      </Directory>

      DocumentRoot "/opt/bitnami/apache/htdocs"

      <Directory "/opt/bitnami/apache/htdocs">
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
      </Directory>

      <IfModule dir_module>
        DirectoryIndex index.html
      </IfModule>

      <Files ".ht*">
        Require all denied
      </Files>

      ErrorLog "logs/error_log"
      LogLevel warn

      <IfModule log_config_module>
        LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
        LogFormat "%h %l %u %t \"%r\" %>s %b" common

        <IfModule logio_module>
          LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O" combinedio
        </IfModule>

        CustomLog "logs/access_log" common
      </IfModule>

      <IfModule alias_module>
        ScriptAlias /cgi-bin/ "/opt/bitnami/apache/cgi-bin/"
      </IfModule>

      <Directory "/opt/bitnami/apache/cgi-bin">
        AllowOverride None
        Options None
        Require all granted
      </Directory>

      <IfModule headers_module>
        RequestHeader unset Proxy early
      </IfModule>

      <IfModule mime_module>
        TypesConfig conf/mime.types
        AddType application/x-compress .Z
        AddType application/x-gzip .gz .tgz
      </IfModule>

      <IfModule proxy_html_module>
        Include conf/extra/proxy-html.conf
      </IfModule>

      <IfModule ssl_module>
        SSLRandomSeed startup builtin
        SSLRandomSeed connect builtin
      </IfModule>

      <IfModule remoteip_module>
        # Trust X-Forwarded-For from ingress-nginx
        RemoteIPHeader X-Forwarded-For
        RemoteIPInternalProxy 10.0.0.0/8
        RemoteIPTrustedProxy  10.0.0.0/8

        LogFormat "%a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined_realip
        CustomLog "logs/access_log" combined_realip
      </IfModule>

      # Includes and defaults
      Include "/opt/bitnami/apache/conf/extra/httpd-default.conf"
      Include "/opt/bitnami/apache/conf/deflate.conf"
      IncludeOptional "/opt/bitnami/apache/conf/vhosts/*.conf"
      Include "/opt/bitnami/apache/conf/bitnami/bitnami.conf"
      Include "/opt/bitnami/apache/conf/bitnami/php.conf"

      PidFile "/opt/bitnami/apache/var/run/httpd.pid"
      TraceEnable Off
      ServerTokens Prod

  valuesFrom:
    - kind: Secret
      name: wordpress-values
