apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb
  namespace: database
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: mariadb
      version: 20.5.7
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      existingSecret: mariadb-secrets
      usePasswordFiles: false
    image:
      repository: bitnami/mariadb
      tag: 11.7.2-debian-12-r0
    primary:
      podAnnotations:
        backup.velero.io/backup-volumes: data
      priorityClassName: "keep-alive"