apiVersion: v1
kind: Secret
metadata:
    name: mariadb-secrets
    namespace: database
type: Opaque
data:
    mariadb-root-password: ENC[AES256_GCM,data:TNErvG2OjP9PRUd2RjfIJFKXNGYsHaDi,iv:xgJ6spx/PwSOQmYWKqEUggi5U8clcmJy9ovzSt1NGcI=,tag:Q4uhTxr4M+Ah6G5olc601Q==,type:str]
sops:
    age:
        - recipient: age1umudqfh963mmhgkgatylwh9jgez7qh4twpaqy3ea3nlcarhm09hq5er32r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMFd4UDcvSE1EZHFpdGJv
            cHN0dlZzcHNUN284MHErS0o2TXVBNFlxK2pvCkkzY2V2NHRYT3UxUlpEdGt5N1I2
            V3Evd0R1ZWJselVBc1lOWitxcjZVYWsKLS0tIFM1dkZtWHA3aGtkS05FOGgyMld0
            ZitEalVIL3Nra0Jnck5LR2R5dG1iSW8KnIogk7hX1gmOl+5ITd5H72jzEEO6dDe9
            TiUaJ37MV9zCNbCS6m7mkWDxaxM7qzfZ5FhoS7q8IpfUTRrrn+KSsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-23T03:49:08Z"
    mac: ENC[AES256_GCM,data:g2BAR+QZpS0i2jwqoBju72ONFiI0X4bIKD9iy0TsXwzNl+qG5eGyXQtcZV52J/qmkoUg412IBaAZJZ5/wMuiCFv8ukGByKkDjQf7IaAoePo51rRGBdBG5h51l3s9QyX0uX6MIp/cdYAN+ebnSzxbql7/RQt8oc9YpCU7+kHuxIo=,iv:p67+OikxKxhnK6Z34c9/UVO2v5y0FblX7+JWpHjdMCk=,tag:HecEChQFwPKYCFzypM3MCg==,type:str]
    encrypted_regex: ^(data|stringData|annotations|)$
    version: 3.10.2
