---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb
  namespace: database
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: mariadb
      version: 20.4.1
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      existingSecret: mariadb-secrets
      usePasswordFiles: false
    image:
      repository: bitnami/mariadb
      tag: 11.7.2-debian-12-r0
    primary:
      podAnnotations:
        backup.velero.io/backup-volumes: data
---
# PostgreSQL for Authentik
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: database
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: postgresql
      version: 16.5.5
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    image:
      repository: bitnami/postgresql
      tag: 15.10.0-debian-12-r2
    auth:
      enablePostgresUser: true
      existingSecret: postgresql-secrets
      secretKeys:
        adminPasswordKey: postgres-password
    primary:
      resources:
        requests:
          cpu: 250m
          memory: 128Mi
      persistence:
        size: 512Mi
      podAnnotations:
        backup.velero.io/backup-volumes: data
      extraEnvVars:
        - name: POSTGRESQL_REPLICATION_USE_PASSFILE
          value: "false"
      extendedConfiguration: |
        max_connections = 500
---
# PostgreSQL 14 for Immich (pgvecto.rs)
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgvectors
  namespace: database
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: postgresql
      version: 16.5.5
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    global:
      security:
        allowInsecureImages: true
    fullnameOverride: pgvectors
    image:
      repository: tensorchord/pgvecto-rs
      tag: pg14-v0.2.0
    auth:
      enablePostgresUser: true
      existingSecret: postgresql-secrets
      secretKeys:
        adminPasswordKey: postgres-password
    primary:
      resources:
        requests:
          cpu: 250m
          memory: 128Mi
      containerSecurityContext:
        readOnlyRootFilesystem: false
      initdb:
        scripts:
          create-extensions.sql: |
            CREATE EXTENSION cube;
            CREATE EXTENSION earthdistance;
            CREATE EXTENSION vectors;
      persistence:
        size: 2Gi
      podAnnotations:
        backup.velero.io/backup-volumes: data
