# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app changedetection
  namespace: changedetection
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: app-template
      version: 4.1.1
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      changedetection:
        strategy: Recreate
        containers:
          app:
            image:
              repository: ghcr.io/dgtlmoon/changedetection.io
              tag: 0.50.3
            env:
              TZ: Australia/Melbourne
              BASE_URL: &host changedetection.k8s.hyde.services
              USE_X_SETTINGS: "1"
              PORT: &port 5000
              PLAYWRIGHT_DRIVER_URL: "ws://localhost:3000?token=TESTING6R0W53R135510"
            probes:
              liveness: &probe
                enabled: true
              readiness: *probe
              startup: *probe
            resources:
              requests:
                cpu: 10m
                memory: 125Mi
            securityContext:
              runAsUser: 1001
              runAsGroup: 1001
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
          browserless:
            image:
              repository: ghcr.io/browserless/chromium
              tag: v2.31.1
            env:
              CONCURRENT: "10"
              DATA_DIR: /profile
              DOWNLOAD_DIR: /downloads
              TOKEN: TESTING6R0W53R135510
            securityContext:
              allowPrivilegeEscalation: false
        pod:
          annotations:
            backup.velero.io/backup-volumes: config
    defaultPodOptions:
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: "OnRootMismatch"
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      app:
        enabled: true
        className: internal-nginx
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Track Website Changes with Automated Monitoring and Alerts
          gethomepage.dev/group: Web Applications
          gethomepage.dev/icon: changedetection
          gethomepage.dev/name: Changedetection
          gethomepage.dev/namespace: changedetection
          gethomepage.dev/app: changedetection
        hosts:
          - host: *host
            paths:
              - path: /
                service:
                  identifier: app
                  port: *port
        tls:
          - secretName: wildcard.hyde.services
            hosts:
              - *host
    persistence:
      config:
        accessMode: ReadWriteOnce
        size: 128Mi
        advancedMounts:
          changedetection:
            app:
              - path: /datastore
      tmpfs:
        type: emptyDir
        advancedMounts:
          changedetection:
            browserless:
              - path: /downloads
                subPath: downloads
              - path: /profile
                subPath: profile
              - path: /config
                subPath: config
