# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app unpackerr
  namespace: media-downloaders
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: app-template
      version: 4.1.1
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      unpackerr:
        strategy: Recreate
        containers:
          app:
            image:
              repository: ghcr.io/unpackerr/unpackerr
              tag: 0.14.5
            env:
              TZ: Australia/Melbourne
              UN_ACTIVITY: "false"
              UN_DEBUG: "false"
              UN_DIR_MODE: "493"
              UN_ERROR_STDERR: "false"
              UN_FILE_MODE: "420"
              UN_INTERVAL: 2m
              UN_LOG_FILES: "10"
              UN_LOG_FILE_MB: "10"
              UN_LOG_QUEUES: 1m
              UN_PARALLEL: "1"
              UN_QUIET: "false"
              UN_RADARR_0_PROTOCOLS: torrent
              UN_RADARR_0_URL: http://radarr.media-managers.svc.cluster.local:7878
              UN_RADARR_1_PROTOCOLS: torrent
              UN_RADARR_1_URL: http://radarr-3d.media-managers.svc.cluster.local:7878
              UN_RETRY_DELAY: 5m
              UN_SONARR_0_PROTOCOLS: torrent
              UN_SONARR_0_URL: http://sonarr.media-managers.svc.cluster.local:8989
              UN_START_DELAY: 1m
              UN_WEBHOOK_0_EVENTS_0: "0"
              UN_WEBHOOK_0_IGNORE_SSL: "false"
              UN_WEBHOOK_0_NAME: Notifiarr
              UN_WEBHOOK_0_SILENT: "false"
            envFrom:
              - secretRef:
                  name: unpackerr-secrets
            resources: {}
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: discovery
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        runAsNonRoot: true
        fsGroup: 1001
        fsGroupChangePolicy: "OnRootMismatch"
    service:
      app:
        enabled: false
    persistence:
      media:
        type: nfs
        server: 10.0.3.7
        path: /mnt/Slow/Media
        globalMounts:
          - path: /data
