# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app phppgadmin
  namespace: database
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: app-template
      version: 4.1.0
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      phppgadmin:
        strategy: Recreate
        containers:
          app:
            image:
              repository: snimshchikov/phppgadmin
              tag: latest # no other tags 🤨
            env:
              PPA_SERVER_DESCS: "postgresql-14"
              PPA_SERVER_HOSTS: "postgresql-14.database.svc.cluster.local"
              PPA_SERVER_PORTS: 5432
              PPA_SERVER_SSL_MODES: "disable"
              PPA_EXTRA_LOGIN_SECURITY: false
            probes:
              liveness: &probe
                enabled: true
              readiness: *probe
              startup: *probe
            securityContext:
              allowPrivilegeEscalation: false
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/arch: "amd64"
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 80
    ingress:
      app:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: "128m"
        className: internal-nginx
        hosts:
          - host: phppgadmin.k8s.hyde.services
            paths:
              - path: /
                service:
                  identifier: app
                  port: *port
        tls:
          - secretName: wildcard.hyde.services
            hosts:
              - phppgadmin.k8s.hyde.services