apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mailserver
  namespace: mailserver
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: docker-mailserver
      version: 4.0.6
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: docker-mailserver
        namespace: flux-system
  values:
    certificate: wildcard.hyde.services
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 1
        memory: 1Gi
    persistence:
      mail-config:
        size: 1Mi
      mail-data:
        size: 256Mi
      mail-state:
        size: 128Mi
      mail-log:
        size: 256Mi
    deployment:
      env:
        # -----------------------------------------------
        # --- Required Section ---------------------------
        # -----------------------------------------------
        OVERRIDE_HOSTNAME: mail.hyde.services

        # -----------------------------------------------
        # --- General Section ---------------------------
        # -----------------------------------------------
        LOG_LEVEL: info
        SUPERVISOR_LOGLEVEL:
        DMS_VMAIL_UID:
        DMS_VMAIL_GID:
        ACCOUNT_PROVISIONER:
        POSTMASTER_ADDRESS:
        ENABLE_UPDATE_CHECK: 0
        UPDATE_CHECK_INTERVAL: 1d
        PERMIT_DOCKER: none
        TZ: Australia/Melbourne
        NETWORK_INTERFACE:
        TLS_LEVEL:
        SPOOF_PROTECTION:
        ENABLE_SRS: 0
        ENABLE_OPENDKIM: 0
        ENABLE_OPENDMARC: 0
        ENABLE_POLICYD_SPF: 0
        ENABLE_POP3:
        ENABLE_IMAP: 1
        ENABLE_CLAMAV: 0
        ENABLE_RSPAMD: 0
        ENABLE_RSPAMD_REDIS: 1
        RSPAMD_LEARN: 0
        RSPAMD_CHECK_AUTHENTICATED: 0
        RSPAMD_GREYLISTING: 0
        RSPAMD_HFILTER: 1
        RSPAMD_HFILTER_HOSTNAME_UNKNOWN_SCORE: 6
        RSPAMD_NEURAL: 0
        ENABLE_AMAVIS: 0
        AMAVIS_LOGLEVEL: 0
        ENABLE_DNSBL: 0
        ENABLE_FAIL2BAN: 0
        FAIL2BAN_BLOCKTYPE: drop
        ENABLE_MANAGESIEVE:
        POSTSCREEN_ACTION: enforce
        SMTP_ONLY:
        # These values are automatically set by the chart based on the certificate key
        # SSL_TYPE:
        # SSL_CERT_PATH:
        # SSL_KEY_PATH:
        SSL_ALT_CERT_PATH:
        SSL_ALT_KEY_PATH:
        VIRUSMAILS_DELETE_DELAY:
        POSTFIX_DAGENT:
        POSTFIX_MAILBOX_SIZE_LIMIT:
        ENABLE_QUOTAS: 1
        POSTFIX_MESSAGE_SIZE_LIMIT:
        CLAMAV_MESSAGE_SIZE_LIMIT:
        PFLOGSUMM_TRIGGER:
        PFLOGSUMM_RECIPIENT:
        PFLOGSUMM_SENDER:
        LOGWATCH_INTERVAL:
        LOGWATCH_RECIPIENT:
        LOGWATCH_SENDER:
        REPORT_RECIPIENT:
        REPORT_SENDER:
        LOGROTATE_COUNT: 4
        LOGROTATE_INTERVAL: weekly
        POSTFIX_REJECT_UNKNOWN_CLIENT_HOSTNAME: 0
        POSTFIX_INET_PROTOCOLS: all
        DOVECOT_INET_PROTOCOLS: all

        # -----------------------------------------------
        # --- SpamAssassin Section ----------------------
        # -----------------------------------------------
        ENABLE_SPAMASSASSIN: 0
        ENABLE_SPAMASSASSIN_KAM: 0
        SPAMASSASSIN_SPAM_TO_INBOX: 1
        MOVE_SPAM_TO_JUNK: 1
        MARK_SPAM_AS_READ: 0
        SA_TAG: 2.0
        SA_TAG2: 6.31
        SA_KILL: 10.0
        SPAM_SUBJECT: "***SPAM*** "

        # -----------------------------------------------
        # --- Fetchmail Section -------------------------
        # -----------------------------------------------
        ENABLE_FETCHMAIL: 0
        FETCHMAIL_POLL: 300
        FETCHMAIL_PARALLEL: 0
        ENABLE_GETMAIL: 0
        GETMAIL_POLL: 5

        # -----------------------------------------------
        # --- LDAP Section ------------------------------
        # -----------------------------------------------
        LDAP_START_TLS:
        LDAP_SERVER_HOST:
        LDAP_SEARCH_BASE:
        LDAP_BIND_DN:
        LDAP_BIND_PW:
        LDAP_QUERY_FILTER_USER:
        LDAP_QUERY_FILTER_GROUP:
        LDAP_QUERY_FILTER_ALIAS:
        LDAP_QUERY_FILTER_DOMAIN:

        # -----------------------------------------------
        # --- Dovecot Section ---------------------------
        # -----------------------------------------------
        DOVECOT_TLS:
        DOVECOT_USER_FILTER:
        DOVECOT_PASS_FILTER:
        DOVECOT_MAILBOX_FORMAT: maildir
        DOVECOT_AUTH_BIND:

        # -----------------------------------------------
        # --- Postgrey Section --------------------------
        # -----------------------------------------------
        ENABLE_POSTGREY: 0
        POSTGREY_DELAY: 300
        POSTGREY_MAX_AGE: 35
        POSTGREY_TEXT: "Delayed by Postgrey"
        POSTGREY_AUTO_WHITELIST_CLIENTS: 5

        # -----------------------------------------------
        # --- SASL Section ------------------------------
        # -----------------------------------------------
        ENABLE_SASLAUTHD: 0
        SASLAUTHD_MECHANISMS:
        SASLAUTHD_MECH_OPTIONS:
        SASLAUTHD_LDAP_SERVER:
        SASLAUTHD_LDAP_BIND_DN:
        SASLAUTHD_LDAP_PASSWORD:
        SASLAUTHD_LDAP_SEARCH_BASE:
        SASLAUTHD_LDAP_FILTER:
        SASLAUTHD_LDAP_START_TLS:
        SASLAUTHD_LDAP_TLS_CHECK_PEER:
        SASLAUTHD_LDAP_TLS_CACERT_FILE:
        SASLAUTHD_LDAP_TLS_CACERT_DIR:
        SASLAUTHD_LDAP_PASSWORD_ATTR:
        SASLAUTHD_LDAP_AUTH_METHOD:
        SASLAUTHD_LDAP_MECH:

        # -----------------------------------------------
        # --- SRS Section -------------------------------
        # -----------------------------------------------
        SRS_SENDER_CLASSES: envelope_sender
        SRS_EXCLUDE_DOMAINS:
        SRS_SECRET:

        # -----------------------------------------------
        # --- Default Relay Host Section ----------------
        # -----------------------------------------------

        DEFAULT_RELAY_HOST:

        # -----------------------------------------------
        # --- Multi-Domain Relay Section ----------------
        # -----------------------------------------------

        RELAY_HOST:
        RELAY_PORT: 25
        RELAY_USER:
        RELAY_PASSWORD:
