apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mailu
  namespace: mailserver
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: mailu
      version: 2.2.2
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: mailu
        namespace: flux-system
  values:
    global:
      database:
        roundcube:
          database: roundcube
          username: roundcube
          existingSecret: mailu-secrets
          existingSecretPasswordKey: ROUNDCUBE_DB_PASS
    hostnames:
      - mail.hyde.services
    domain: hyde.services
    existingSecret: mailu-secrets
    timezone: Australia/Melbourne
    initialAccount:
      enabled: true
      username: alex
      domain: hyde.services
      existingSecret: mailu-secrets
      existingSecretPasswordKey: INITIAL_ADMIN_PW
      mode: ifmissing
    subnet: 10.233.64.0/18
    subnet6: fd85:ee78:d8a6:8607::1:0000/112
    mailuVersion: "2024.06.36"
    logLevel: WARNING
    dmarc:
      rua: ""
      ruf: ""
    limits:
      messageSizeLimitInMegabytes: 64
      authRatelimit:
        ip: 60/hour
        ipv4Mask: 24
        ipv6Mask: 56
        user: 100/day
        exemptionLength: 86400
        exemption: ""
      messageRatelimit:
        value: 200/day
        exemption: ""
    customization:
      siteName: Mailu
      website: https://mail.hyde.services
      logoUrl: none
      logoBackground: none
    externalDatabase:
      enabled: true
      type: mysql
      host: mariadb.database.svc.cluster.local
      port: 3306
      existingSecret: mailu-secrets
      existingSecretDatabaseKey: MAILU_DB
      existingSecretUsernameKey: MAILU_DB_USER
      existingSecretPasswordKey: MAILU_DB_PASS
    persistence:
      single_pvc: false
    ingress:
      enabled: true
      ingressClassName: external-nginx
      pathType: ImplementationSpecific
      path: /
      existingSecret: wildcard.hyde.services
      tls: true
      realIpHeader: X-Forwarded-For
      realIpFrom: 0.0.0.0/0
      extraHosts:
        - name: mailu.hyde.services
          path: /
      extraTls:
        - hosts:
            - mailu.hyde.services
          secretName: wildcard.hyde.services
    front:
      logLevel: WARNING
      hostPort:
        enabled: false
      externalService:
        enabled: true
        type: LoadBalancer
        annotations:
          metallb.io/loadBalancerIPs: 192.168.4.13
        ports:
          pop3: false
          pop3s: true
          imap: false
          imaps: true
          smtp: true
          smtps: true
          submission: true
          manageSieve: true
      kind: Deployment
      replicaCount: 1
      updateStrategy:
        type: Recreate
    admin:
      enabled: true
      uri: /admin
      logLevel: INFO
      updateStrategy:
        type: Recreate
      persistence:
        size: 1Gi
      extraEnvVars:
        - name: DB_APPENDIX
          value: "?collation=utf8mb4_unicode_ci"
    redis:
      enabled: true
      architecture: standalone
      auth:
        enabled: false
      master:
        enabled: true
        count: 1
        persistence:
          enabled: false
          size: 8Gi
      replica:
        count: 0
    postfix:
      logLevel: INFO
      updateStrategy:
        type: Recreate
      persistence:
        size: 1Gi
    dovecot:
      enabled: true
      logLevel: INFO
      updateStrategy:
        type: Recreate
      persistence:
        size: 10Gi
      compression: lz4
      compressionLevel: 6
    rspamd:
      overrides: {}
      antivirusAction: discard
      logLevel: INFO
      persistence:
        size: 1Gi
      updateStrategy:
        type: Recreate
    clamav:
      enabled: true
      logLevel: INFO
      image:
        repository: clamav/clamav-debian
        tag: 1.4.2-42
        pullPolicy: IfNotPresent
      persistence:
        size: 1Gi
    webmail:
      enabled: true
      uri: /webmail
      type: roundcube
      roundcubePlugins:
        - archive
        - zipdownload
        - markasjunk
        - managesieve
        - enigma
        - carddav
        - vcard_attachments
        - mailu
      logLevel: INFO
      persistence:
        size: 1Gi
      updateStrategy:
        type: Recreate
    webdav:
      enabled: false
      logLevel: INFO
      updateStrategy:
        type: Recreate
    fetchmail:
      enabled: true
      delay: 600
      persistence:
        size: 512Mi
      logLevel: INFO
      updateStrategy:
        type: Recreate
    tika:
      enabled: true
      logLevel: INFO
      languages:
        - en
      image:
        repository: apache/tika
        tag: 3.1.0.0-full
        pullPolicy: IfNotPresent
        registry: docker.io
