apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: vars
    namespace: flux-system
spec:
    interval: 5m0s
    path: ./cluster/homelab/base/vars
    prune: true
    decryption:
        provider: sops
        secretRef:
            name: sops-age
    sourceRef:
        kind: GitRepository
        name: flux-system