apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pterodactyl-panel
  namespace: pterodactyl
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: pterodactyl-panel
      version: 0.2.2
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: hydaz
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/pterodactyl/panel
      tag: v1.11.11
    panel:
      app:
        timezone: Australia/Melbourne
      database:
        host: mariadb.database.svc.cluster.local
        port: 3306
        name: pterodactyl
        existingSecret:
          name: &secret pterodactyl-secrets
          usernameKey: dbUser
          passwordKey: dbPassword
      mail:
        driver: smtp
        from: no-reply@hyde.services
        host: mail.hyde.services
        port: 465
        existingSecret:
          name: *secret
          usernameKey: mailUser
          passwordKey: mailPassword
    lifecycle:
      postStart:
        exec:
          # jankiest way of installing extentions
          command:
            - /bin/sh
            - -c
            - |
              if [ ! -f /app/.theme-installed ]; then
                apk add --no-cache rsync yarn

                cd /app
                php artisan config:clear
                php artisan config:cache
                php artisan optimize

                rsync -a /app/var/arix/theme/ /app/
                rsync -a /app/var/arix/addon/ /app/

                export NODE_OPTIONS=--openssl-legacy-provider
                printf "\n0\n" | php artisan arix install
                printf "\n0\n\n" | php artisan addons install

                touch /app/.theme-installed
              fi
    ingress:
      main:
        enabled: true
        ingressClassName: external-nginx
        hosts:
          - host: &host pterodactyl.hyde.services
            paths:
              - path: /
        tls:
          - secretName: wildcard.hyde.services
            hosts:
              - *host
    resources:
      requests:
        cpu: 300m
        memory: 128Mi
    persistence:
      data:
        enabled: true
        accessMode: ReadWriteOnce
        size: 1Gi
      nginx:
        enabled: true
        accessMode: ReadWriteOnce
        size: 64Mi
      certs:
        enabled: true
        accessMode: ReadWriteOnce
        size: 64Mi
      logs:
        enabled: true
        accessMode: ReadWriteOnce
        size: 512Mi
    wings:
      enabled: true
      ingressClassName: internal-nginx
      tlsSecretName: wildcard.hyde.services
      corsAllowOrigin: https://pterodactyl.hyde.services
      instances:
        - name: discovery
          ip: 192.168.100.7
          port: 8080
          to: discovery.wing.hyde.services
        - name: oci1
          ip: 207.211.147.226
          port: 8080
          to: oci1.wing.hyde.services
