apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: media-downloaders
    namespace: media-downloaders
spec:
    interval: 5m
    install:
        createNamespace: true
    chart:
        spec:
            chart: ./Helm/apps/media-downloaders
            reconcileStrategy: Revision
            sourceRef:
                kind: GitRepository
                name: flux-system
                namespace: flux-system

