apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wordpress
resources:
  - ../../base
patches:
  - target:
      kind: HelmRelease
      name: wordpress
    patch: |-
      - op: replace
        path: /metadata/name
        value: wordpress1
      - op: replace
        path: /spec/valuesFrom/0/name
        value: wordpress1-values
secretGenerator:
  - name: wordpress1-values
    files:
      - values.yaml=values.sops.yaml
    options:
      disableNameSuffixHash: true
