# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: ENC[AES256_GCM,data:RbF7cw==,iv:0sdj6NIKACAfmq4qTFNgW0yMS09OlNaukqKWerEki9s=,tag:+qUnqUA8Gol4SyeVUs1LxQ==,type:str]
    namespace: ENC[AES256_GCM,data:WRD6UfHBI3YTCcgcYw==,iv:ZW6XklxMCmFnlW3Ud63LyHUW6xwfiSXQ9BlUi+gWnH4=,tag:HwYeWWS6KETjamKztMB+nA==,type:str]
spec:
    interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    chart:
        spec:
            chart: app-template
            version: 4.0.1
            interval: 5m
            sourceRef:
                kind: HelmRepository
                name: bjw-s
                namespace: flux-system
    values:
        controllers:
            xbvr:
                strategy: ENC[AES256_GCM,data:vlGJG5ttt0k=,iv:zHt9ZIpEJ83KJU8ckwcMPMFrGBhOjyIFgw8FGN5Jqjg=,tag:fGLj0HTKsbn80JLCiPdMpg==,type:str]
                containers:
                    app:
                        image:
                            repository: ENC[AES256_GCM,data:iYcnxtp6I0Ss9cNLkv+jbKY34g==,iv:0AXT5s/TMIhHBSqRUmzqLrzxQu9jPiNQeu+o8Q7WKUo=,tag:R+CnGTRkoxdtP5sc3XloLg==,type:str]
                            tag: ENC[AES256_GCM,data:Npf81Yuj,iv:MvS+ICBvKVXp4ajMm2nk6cBY42nzkCAsi+iOuLsXMF0=,tag:E9I7GHnqSVsoenIKhI3vow==,type:str]
                            pullPolicy: ENC[AES256_GCM,data:0ye4Q2go,iv:kOsWMZnbJWKa8Ph6Bs2azF5YTz6wwyAPgxgiChaqTPA=,tag:0H5fy/5GFd8ZGVrXOjIcVw==,type:str]
                        env:
                            TZ: ENC[AES256_GCM,data:/jAHC0lYIJvgBZWYvf1W1SAbUg==,iv:VEPvGegT1uvkz+Wduj2OusrDMXMyu7w4yS8kChEECyc=,tag:TeMfWV1xKAVx8ziqSqF01A==,type:str]
                            HOME: ENC[AES256_GCM,data:c3X8ptRFqg==,iv:KX1lxWWNwqztjbOD1VLrqRnASpk7LNhxVeL+iAbkbvA=,tag:DVJyy5hR1NSnetFtsfF92w==,type:str]
                        probes:
                            liveness:
                                enabled: ENC[AES256_GCM,data:QE4u5A==,iv:aJJnRMfoGd0jBatcgcMmC8Had28omHDU1+LzjfuCg5o=,tag:7n80Wi4PwsqK3EZIxhRGOw==,type:bool]
                            readiness:
                                enabled: ENC[AES256_GCM,data:H8Fk2w==,iv:/LavG2Oh7K5H3lOK3Ugl8xAv4QsO9NDSimQUh0vJPJI=,tag:M1TChNJuD55kuP9F4CFb0g==,type:bool]
                            startup:
                                enabled: ENC[AES256_GCM,data:xJbAcg==,iv:WYz8IIh0/lazfnpwQZh6IDSCwZubE0KA5r2oZ+Q4ZCo=,tag:jO+jQOs/ubbWs/UpTFSHHw==,type:bool]
                        resources:
                            requests:
                                cpu: ENC[AES256_GCM,data:GIQX,iv:5sbzKKPd5Xmf97gdKLDJgHPt5NJD0WIYQT5xvZHOnQ4=,tag:9XY/3UnaRfN8/fxOo8AEcA==,type:str]
                                memory: ENC[AES256_GCM,data:z3TG1fY=,iv:avvkjfS4bMq5gnzNP2b7W1Hkw7ETFF4q5TFrSPzaJ6Y=,tag:iZtt6iMGL0LSSPTQvwiUow==,type:str]
                        securityContext:
                            allowPrivilegeEscalation: ENC[AES256_GCM,data:c4dkZ9M=,iv:BhXT2c2y+qkEi0g4U34rSwhkRdppbFjbvd6qFDfHxxQ=,tag:19Ib9R6tA87wr+3nL5aHqQ==,type:bool]
                            capabilities:
                                drop:
                                    - ENC[AES256_GCM,data:0919,iv:WGH3nFUJOxoRcGrriLB2dA3C2jJFgapo6qj10vrlH4Q=,tag:2rNo6IIsL+dyR42FTvxvoQ==,type:str]
        defaultPodOptions:
            annotations:
                backup.velero.io/backup-volumes: ENC[AES256_GCM,data:IuJO8QMf,iv:WjhSCBZ9+087dGcEx3aTbw+Uj6MrraYoGhhHQ61kQ3I=,tag:lYQD26+Z8ywMiw2ParZbkA==,type:str]
            nodeSelector:
                kubernetes.io/arch: ENC[AES256_GCM,data:bvzJf5k=,iv:R1NWfrwWibQMxPb/PLoEgmG9Y7eE3SPw7n5xwNwAIJc=,tag:Fyh5WMJgB4nf5I+3SQz/Eg==,type:str]
            securityContext:
                runAsUser: ENC[AES256_GCM,data:05gIBQ==,iv:Lw9x8wWl5Md9Z0Eie1jfbSjVvwHs+w6rc2hQiBX33r8=,tag:bAD6pPgK+DA0dHihchcU6Q==,type:int]
                runAsGroup: ENC[AES256_GCM,data:fu//lg==,iv:99iOaKVGO+z2qoDuRPOmblJ5KznHU1wWpuVi2faj7k4=,tag:ZYK6hEGmTeomrR4bVG15dw==,type:int]
                runAsNonRoot: ENC[AES256_GCM,data:CkhPkQ==,iv:5aBXjh31gjEQJo8OVHDAnlSo4q+aktu6a3lBCMHSBas=,tag:lOivD8+D5rn0Plzpi+8CLw==,type:bool]
                fsGroup: ENC[AES256_GCM,data:hhVAKg==,iv:kOYfAzdCrPORatVRh7ajFmC86qbVux3wGy+L1yqjL9w=,tag:HFnxA78L8Xe/aSGhcQxMNQ==,type:int]
                fsGroupChangePolicy: ENC[AES256_GCM,data:DYgr+1TJNCk9juefbkc=,iv:PUJ5TLNSq8/wHV0R9/2QgQWbTjZ/B2/O+Ennybr9GUI=,tag:jpmvFMS3Ne7jDSV/7oP1CQ==,type:str]
        service:
            app:
                controller: ENC[AES256_GCM,data:WB7tNg==,iv:fB2UECmPXlnvNgxjAtTXBz1acn+sq9a3Flv7UTUEJQg=,tag:18Dy20FRR+9ZKksZh2bTGA==,type:str]
                ports:
                    http:
                        port: ENC[AES256_GCM,data:A6X7eQ==,iv:2oWrwJnEmfeCC/Dyd7S6+GMW0YNaae2svvOjrFZ1xxk=,tag:wj82gDOL/F2IQqivTHv3+A==,type:int]
        ingress:
            app:
                enabled: ENC[AES256_GCM,data:NF+HFQ==,iv:fKbTmmjzK8pkwagOdObZtAeBPwDJlRvEIjm2HcfuoKw=,tag:BHuQUsZMi2bge5cLejHICw==,type:bool]
                className: ENC[AES256_GCM,data:N8vcDCdFAtk8ttojy3g=,iv:Kg6D74ixGPhOh5YWjuFCrL+7ASy9IgeS+SD+dYKKDTc=,tag:sJq0yokMfPiMmupqcJTjcw==,type:str]
                hosts:
                    - host: ENC[AES256_GCM,data:+TCAXe5aBYWh2Uev095uA+dYHnXhdg==,iv:AdgjJXoiHgw1S0ofDyH5hdb+OVIiksZIxudAGA+TJAU=,tag:rP6uNLlMF2mYWSw06/UZBg==,type:str]
                      paths:
                        - path: ENC[AES256_GCM,data:nQ==,iv:IjgqR1cz3yqC99tKc6LaCzxMscoptnDlRxkfXfq9dmA=,tag:zcbRJq8H7hGIbLCe9go79w==,type:str]
                          service:
                            identifier: ENC[AES256_GCM,data:mVxf,iv:u3a2N8ec9d5tUPJ97DovCueMyrohJdXAGTw/G/B7sOg=,tag:UubUEqpcTGjtbwANQo+5tw==,type:str]
                            port: ENC[AES256_GCM,data:8YIFMQ==,iv:/0Zs57LAOB6OdKN2pO2X6fGBJnwywHg8HTsQFDulrLU=,tag:7Lo/jKbV35jSzp+gQzNwIA==,type:int]
                tls:
                    - secretName: ENC[AES256_GCM,data:sx6f2PA82BEIsHHrrqw7rXMnPGseWQ==,iv:oY7POsLb8KjUwOiUgl0gDf1Yiw+D73dH+Q0RwNMHhO0=,tag:s3Xd39RyG03Qiteo0rFCJA==,type:str]
                      hosts:
                        - ENC[AES256_GCM,data:lov1S71dT/cQ/GOtV/DBeWOQADnX6g==,iv:tLhhbziofLnI1ZJFvJVdCS5scL+VsjaorIufOIJo3zk=,tag:IzwTBZVJ/ebUaNx8ijh8QQ==,type:str]
        persistence:
            config:
                globalMounts:
                    - path: ENC[AES256_GCM,data:1Xt8OY46bKgHIo2sUI5z,iv:4WnYsqiyhrLaZvQtG0ITW98YW19/fCBXvbxNum43WP4=,tag:nLeY6LYF17tAooxrmGNXAg==,type:str]
                accessMode: ENC[AES256_GCM,data:UxQasY85bMBDdF5hpQ==,iv:2BB0dBlmdFdiQog4GujtDN6SCHpJbOxjD88HaOctR+k=,tag:atsWzo7kujeKf5/hv3Q3Dw==,type:str]
                size: ENC[AES256_GCM,data:KMIg,iv:aWzxgj/KXrp1lsSdUnHwPEedkKc0GarYWICpjmD1N3o=,tag:K8aNMwG8yCnWV3A6PEIRPQ==,type:str]
            media:
                type: ENC[AES256_GCM,data:MwW+,iv:jKhI89gcANCG925R7cYBFFHjnKOZhmA3azY6Y4729do=,tag:+7Tc9lgAYnrKhgU1itNCPw==,type:str]
                server: ENC[AES256_GCM,data:B/vhPoZpZos=,iv:Dzl3z8VkOXnzHAAtBWsXbC0hEaXtpSqnw03Vr30AcrY=,tag:rxBOsmhOoLTcJ3R4YOTPaA==,type:str]
                path: ENC[AES256_GCM,data:9XsTzXmlCzYRp6kln83K2HYw6jQj2WGk,iv:SlB+CTNYASEAIU9enUv60nSMJ+YlFYaPuBJRvniLykE=,tag:6SQH6akVEq8pWPK9uQKkLA==,type:str]
                globalMounts:
                    - path: ENC[AES256_GCM,data:IZF7QnDGmg==,iv:vzaau68t10fl5jQO5SKp4wbqB4gnvh+X2xVVRsDffoA=,tag:c9oM2JROFGFNGWcd2x17iQ==,type:str]
sops:
    age:
        - recipient: age1umudqfh963mmhgkgatylwh9jgez7qh4twpaqy3ea3nlcarhm09hq5er32r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDa2hEZ2ZjeUF6VjBEUU83
            UGVEZmVLNWZwYmExVEVKdUV2cU91bnVIUlZNCkc2Z0srT2xRY2I1VHhEVjJteEZ2
            M092WHg0SEFQd1IvN0dIZEhPRVFoRWsKLS0tIFc0ci9kcnF3RGpLT2RORGRPdnJD
            YlZ0ZDdvcmI5QzNheEFKdk5pQWtHZncK3P2+vWqQooaU4WWMKw7nGtcnU2zL8N4h
            B1gtAPhr261+YSOvNEug2+wFACulyT/1MZ+dR14xJm+7PmpnMMF3Lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-11T04:24:23Z"
    mac: ENC[AES256_GCM,data:HiZTXEQ1U38tBKPVPwmwklCRuDhh1dLJqYgNkeQxTBjFzKMHHym3Mcs+gzHZPOoCTvJ9kKsCeEMmcDCi8ZsOSk07sY2ir/VRw5RGaIvlDPFVP3Dhdy7rvh15hs2aBiF8BIYjAupLcyD+DktgorT+h14EBwcbfahFWYeiP6+BHz8=,iv:wwlH6IW5KpS3i9NI9j7162jmeaF5XA/dLZa6nzaMQxs=,tag:pI+YQ58oVF12Ii/LLMFrDA==,type:str]
    encrypted_regex: (metadata|values)
    version: 3.10.2
