---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: homepage
      version: 2.0.1
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/gethomepage/homepage
      tag: v1.0.4
    enableRbac: true
    serviceAccount:
      name: homepage
      create: true
    service:
      main:
        ports:
          http:
            port: 3000
    controller:
      strategy: Recreate
    ingress:
      main:
        enabled: false
    config:
      useExistingConfigMap: homepage-config
    persistence:
      logs:
        enabled: true
        type: emptyDir
        mountPath: /app/config/logs
    resources:
      requests:
        memory: 128Mi
        cpu: 10m
