apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql-14
  namespace: database
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: postgresql
      version: 16.7.2
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    image:
      registry: ghcr.io
      repository: hydazz/bitnami-postgres-pgvecto-rs
      tag: 14.17.0-debian-12-r14
    auth:
      enablePostgresUser: true
      existingSecret: postgresql-secrets
      secretKeys:
        adminPasswordKey: postgres-password
    global:
      security:
        allowInsecureImages: true
    primary:
      resources:
        requests:
          cpu: 250m
          memory: 128Mi
      persistence:
        size: 2Gi
      podAnnotations:
        backup.velero.io/backup-volumes: data
      extraEnvVars:
        - name: POSTGRESQL_REPLICATION_USE_PASSFILE
          value: "false"
      extendedConfiguration: |
        max_connections = 500
      initdb:
        scripts:
          create-extensions.sql: |
            CREATE EXTENSION cube;
            CREATE EXTENSION earthdistance;
            CREATE EXTENSION vectors;
      priorityClassName: "keep-alive"
