apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ${D_HCA//./-} # security over reliability
  namespace: wordpress
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: wordpress
      version: 24.2.11
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    image:
      repository: bitnami/wordpress
      tag: 6.8.1-debian-12-r6
    mariadb:
      enabled: false
    memcached:
      enabled: false
    externalCache:
      host: memcached.wordpress.svc.cluster.local
      port: 11211
    podAnnotations:
      backup.velero.io/backup-volumes: wordpress-data
    fullnameOverride: *app
    networkPolicy:
      enabled: false
    wordpressConfigureCache: true
    overrideDatabaseSettings: true
    htaccessPersistenceEnabled: true
    wordpressScheme: https
    allowEmptyPassword: false
    readinessProbe:
      httpGet:
        path: /
    resourcesPreset: medium
    updateStrategy:
      type: Recreate
    service:
      type: ClusterIP
    priorityClassName: keep-alive
    externalDatabase:
      host: mariadb.database.svc.cluster.local
      port: 3306
      user: &dbUser ${D_HCA//./_}
      database: *dbUser
      existingSecret: "hca-secrets"
    ingress:
      enabled: true
      ingressClassName: external-nginx
      hostname: &host ${D_HCA}
      tls: true
      extraTls:
        - hosts:
            - *host
          secretName: wildcard.${D_HCA}
    persistence:
      size: 1Gi

  valuesFrom:
    - kind: ConfigMap
      name: apache-config
