apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 74.2.1
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    grafana:
      defaultDashboardsTimezone: Australia/Melbourne
      ingress:
        enabled: true
        ingressClassName: internal-nginx
        hosts:
          - &grafanaHost grafana.k8s.hyde.services
        paths:
          - /
        tls:
          - secretName: &tlsSecret wildcard.hyde.services
            hosts:
              - *grafanaHost
      persistence:
        enabled: true
        accessModes:
          - ReadWriteOnce
        size: 128Mi
      deploymentStrategy:
        type: Recreate
    prometheus:
      ingress:
        enabled: true
        ingressClassName: internal-nginx
        hosts:
          - &prometheusHost prometheus.k8s.hyde.services
        paths:
          - /
        tls:
          - secretName: *tlsSecret
            hosts:
              - *prometheusHost
