apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wordpress
resources:
  - ../../base
patches:
  - target:
      kind: HelmRelease
      name: wordpress
    patch: |-
      - op: replace
        path: /metadata/name
        value: livemusicvictoria-com-au
      - op: replace
        path: /spec/valuesFrom/0/name
        value: livemusicvictoria-com-au-values
secretGenerator:
  - name: livemusicvictoria-com-au-values
    files:
      - values.yaml=values.sops.yaml
    options:
      disableNameSuffixHash: true
