apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: semaphore
  namespace: knick-knacks
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: ansible-semaphore
      version: 12.12.9
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: cloudhippie
        namespace: flux-system
  values:
    fullnameOverride: semaphore
    image:
      repository: semaphoreui/semaphore
      tag: v2.13.14
    admin:
      create: true
      existingSecret: "semaphore-secrets"
      emailKey: "adminemail"
      fullnameKey: "adminfullname"
      usernameKey: "adminusername"
      passwordKey: "adminpassword"
    database:
      type: "mysql"
      host: "mariadb.database.svc.cluster.local"
      port: "3306"
      name: "semaphore"
      usernameFromSecret: false
      username: "semaphore"
      existingSecret: "semaphore-secrets"
      passwordKey: "dbpassword"
    ingress:
      enabled: true
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Modern web interface for managing popular DevOps tools
        gethomepage.dev/group: Web Applications
        gethomepage.dev/icon: semaphore
        gethomepage.dev/name: Semaphore
        gethomepage.dev/namespace: knick-knacks
        gethomepage.dev/app: ansible-semaphore
      className: internal-nginx
      hosts:
        - host: semaphore.k8s.hyde.services
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - semaphore.k8s.hyde.services
          secretName: wildcard.hyde.services
    persistence:
      enabled: true
      size: "64Mi"
