apiVersion: v1
kind: Secret
metadata:
    name: semaphore-secrets
    namespace: knick-knacks
type: Opaque
stringData:
    adminemail: ENC[AES256_GCM,data:gchSYen/BSwpindCXyl2Dxd/vWIpNDW8,iv:x6qvsmkP9US8WUaITu55APREv7U+Er9gjdIWz0vytCs=,tag:biz5QIfRGr21LHcLV8s3lA==,type:str]
    adminfullname: ENC[AES256_GCM,data:VW14g2uJJn+m,iv:nsJyWph6cymEvQYZi7pM/8/bUOTx9TiWAqwczXX0swc=,tag:qnt7McSM1+2cvAqTjyx7pA==,type:str]
    adminusername: ENC[AES256_GCM,data:TRRGCw==,iv:1MbspUu3ThaJYB/uKGSDV8MahiMCO5MLhiav/E8lg40=,tag:FqZkPvfN77E0Gs8qkCQaYQ==,type:str]
    adminpassword: ENC[AES256_GCM,data:yHoXKoaHDGmKVzXU,iv:tAmJEeaJELcFPsF1YixqzacTfPR+O7OTNUCQQ0lHEwA=,tag:FGISNLbN5t6TJ5ldyuwXVw==,type:str]
    dbpassword: ENC[AES256_GCM,data:DPC0lBPX6plmqgLRWfc=,iv:YDeAErLCN8xA/UMybEMVT6aULbZreHxiYzuwxH6iXOo=,tag:BuyBbBpQ2qH8lCLrgpAp2g==,type:str]
sops:
    age:
        - recipient: age1umudqfh963mmhgkgatylwh9jgez7qh4twpaqy3ea3nlcarhm09hq5er32r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMFd4UDcvSE1EZHFpdGJv
            cHN0dlZzcHNUN284MHErS0o2TXVBNFlxK2pvCkkzY2V2NHRYT3UxUlpEdGt5N1I2
            V3Evd0R1ZWJselVBc1lOWitxcjZVYWsKLS0tIFM1dkZtWHA3aGtkS05FOGgyMld0
            ZitEalVIL3Nra0Jnck5LR2R5dG1iSW8KnIogk7hX1gmOl+5ITd5H72jzEEO6dDe9
            TiUaJ37MV9zCNbCS6m7mkWDxaxM7qzfZ5FhoS7q8IpfUTRrrn+KSsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-09T09:32:30Z"
    mac: ENC[AES256_GCM,data:brEB4wBjd6PeZfZ5J6sGskBMprJgQhFfIx3FXOV/V4t9HLB4rj4StwkqrmXzEcwwMsty6NFBipgPLYVc9mzD1XmVBZ/mwRATgv8De7cZ9/bqbQiTFeHnm1bkFjprQnzp73n0VrwonXfIB1GSRwAdSRF+QR6AhP5kQSVuE/M+KpA=,iv:+/NnnEzkN4bX+cMtCD01gFJ9I1Eq2SqspOPmYhGkirk=,tag:ZzXngizRteyZmOFkfQY/yQ==,type:str]
    encrypted_regex: ^(data|stringData|annotations|)$
    version: 3.10.2
