apiVersion: v1
kind: Secret
metadata:
    name: unifi-protect-credentials
    namespace: knick-knacks
data:
    UFP_USERNAME: ENC[AES256_GCM,data:H8QKq1WpW6Y=,iv:dr+K2NtyFWm2GETml3xJxy+4CKKwym1tElXu5iItRtc=,tag:f1Nk8OwaxHfd+eC61W/XdQ==,type:str]
    UFP_PASSWORD: ENC[AES256_GCM,data:708kNFeqLTbGr4C4Bdfc1ssYlHZldZMPp9o+kWNhI592UJ311dqFB9zjFvc=,iv:GaVdiFl9cC2r8bR78f9MCRBVV5noU9nk5e8Hv7fVwaU=,tag:5HRbtwBGIw0/BLIA1QOZFA==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1umudqfh963mmhgkgatylwh9jgez7qh4twpaqy3ea3nlcarhm09hq5er32r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMFd4UDcvSE1EZHFpdGJv
            cHN0dlZzcHNUN284MHErS0o2TXVBNFlxK2pvCkkzY2V2NHRYT3UxUlpEdGt5N1I2
            V3Evd0R1ZWJselVBc1lOWitxcjZVYWsKLS0tIFM1dkZtWHA3aGtkS05FOGgyMld0
            ZitEalVIL3Nra0Jnck5LR2R5dG1iSW8KnIogk7hX1gmOl+5ITd5H72jzEEO6dDe9
            TiUaJ37MV9zCNbCS6m7mkWDxaxM7qzfZ5FhoS7q8IpfUTRrrn+KSsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-11T04:13:01Z"
    mac: ENC[AES256_GCM,data:sK+PvRYdG9tCH9vYQiW3g4vUNnsjqi8awO0zWTq5LZccPkwiFcdjTyXB6tzG9dboUnPR7q3Nzv5/96PMV6uXq7Bd55ZqQI6xqxNz97bi71Y2Kc3eMoWFgwy49XVuYbXjegFGhodhpp+Epng1D9CIBKkiQtHHZHic4l3w1tvWfw8=,iv:4tHhQRY1PWQHYmsaHKlu2Y30slcGwLvV2kCwY5lth6c=,tag:wWWPGN6nR/kLsHi+LY37Zg==,type:str]
    encrypted_regex: ^(data|stringData|annotations|)$
    version: 3.10.1
