apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: reflector
      version: 9.1.11
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: reflector
        namespace: flux-system
  values:
    livenessProbe:
      periodSeconds: 30
    readinessProbe:
      periodSeconds: 10
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
