# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: ENC[AES256_GCM,data:cNZjpj2WrBM=,iv:Y3q3oMKJTLN5RGTmdQfM/7+/gXrxSeawsDysTGQt5mE=,tag:FNAyUD8peCAJg91DMBIkHw==,type:str]
    namespace: ENC[AES256_GCM,data:orjmV7XeHKcvMeqOqzg=,iv:iXROFzctJic82pDOLb6hY2EsnC5r5nIo6+9yvxl61vI=,tag:heTsDosTj5KhrNGfvEF4Ng==,type:str]
spec:
    interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    chart:
        spec:
            chart: app-template
            version: 4.1.1
            interval: 5m
            sourceRef:
                kind: HelmRepository
                name: bjw-s
                namespace: flux-system
    values:
        controllers:
            whisparr:
                strategy: ENC[AES256_GCM,data:MnqnYB/ngcc=,iv:uqCr5fiNgliaxILKDeC+jI/asBO6ULHRYgGJgGuv5Ok=,tag:gK3gHs0PicN0JcUu96F+gg==,type:str]
                containers:
                    app:
                        image:
                            repository: ENC[AES256_GCM,data:gnVxeCv+hPx5hSN6opjXxE1Zxx+tfg==,iv:UrajEHMFQQY+zM3UovVpYLkbgtnIs5WcOINni2wjv6o=,tag:ianb3Wlx6boTw6IU5mEykg==,type:str]
                            tag: ENC[AES256_GCM,data:6Lg=,iv:GoEGDbFHqBsdygDYdpRqwOJD02ckFR1AFXKAyI1J4X0=,tag:RIHM6UYxCLt67d4pUr5TIA==,type:str]
                            pullPolicy: ENC[AES256_GCM,data:eHESarEo,iv:xNVFDSRXzsjZpt4ZKRLBpivhBQ8+AjrcmXZ/jMAmK00=,tag:GcTESurfNED5wx6aPDQnrA==,type:str]
                        env:
                            TZ: ENC[AES256_GCM,data:9uMYXjlPF8SuQtw/8TaftFkU+w==,iv:ubADVQQHdIFTeke08l79dFjzRAYNaw0t/fbaAnohqSs=,tag:FcdmeaCj/KIjPNYsTE5RlA==,type:str]
                            PUID: ENC[AES256_GCM,data:eKYb6Q==,iv:p7XU8ylGhh2Yy8iDkU9SpNaSa4eiKoS+ra5XVDrSspI=,tag:zqWajWi4r11a7avc0kahZQ==,type:int]
                            GUID: ENC[AES256_GCM,data:BQGYxg==,iv:Fo2YkSfNWyWNY6OaOleFVY9E/IbVvy29abuDm9Zs0Bs=,tag:FxgRZAIN0mcvzZW14OEf1A==,type:int]
                        probes:
                            liveness:
                                enabled: ENC[AES256_GCM,data:xNo0OA==,iv:S/qJDpXUVHdCwjjo3Z5JqeTgBjYukXF3ltcecjEmSd0=,tag:q3dSMW1iLU5qU57XRdyb6w==,type:bool]
                                custom: ENC[AES256_GCM,data:Ebv9GQ==,iv:LWmqW1DlhlKKY3tW4N1cc/rnsLXEDnMlr9xuipT4M+M=,tag:qUJtrB1Tyx+ef4i+1ertSA==,type:bool]
                                spec:
                                    httpGet:
                                        path: ENC[AES256_GCM,data:3+8Q870=,iv:/4zen2ivQgzA0J4sJQdmUJ2Kz1Z56HrWiuK1/mT+J8w=,tag:Bmsqzf6i2EqUG5RzTTqGKA==,type:str]
                                        port: ENC[AES256_GCM,data:068zVQ==,iv:qpcAwytXft2mqZmcq5NdxAT4T9ohZH79ILr1780yLXA=,tag:RLprUJoYeSLGeipklvLg2w==,type:int]
                            readiness:
                                enabled: ENC[AES256_GCM,data:D+4H8w==,iv:UDpQWxP/kggkmFDT4oewQlsqdyF97hDxCsLZM+zhhNI=,tag:72KBh5+5bfXeOIWl3zJuSQ==,type:bool]
                                custom: ENC[AES256_GCM,data:OBQaGQ==,iv:i/D2HBfj5wY9kVynNgKAXTLAK61y+hm0P58nD0+S9Ik=,tag:2D/7WSwYoyJrtNFuCfoluA==,type:bool]
                                spec:
                                    httpGet:
                                        path: ENC[AES256_GCM,data:NEpwJoA=,iv:Vy17ZI44i6HiY24uF1MXAyBI3EzRdocvaMSeWpQXXVI=,tag:EXa7Hw0joVHG5bcJRYNRww==,type:str]
                                        port: ENC[AES256_GCM,data:IQgrwA==,iv:2skaHokzVw3lxHbH5bOxL0UJ/+4XZ1rGKIIJtoqREfs=,tag:429ZA+2/EnMlUxfh7wMXaA==,type:int]
                        resources:
                            requests:
                                cpu: ENC[AES256_GCM,data:Ofe+sQ==,iv:ooSwBc+3P1NwT8qVYlAJVXNmU5FuIYy09uMXgteEPxQ=,tag:pOJAMYtEJhU43SOreRpLhw==,type:str]
                                memory: ENC[AES256_GCM,data:z+e9JgA=,iv:gucvdZU6Ol378I8VIKLO7/FlbYmg6wtYmh62yavJ6Cg=,tag:RSZ4JzNnvM+gV9vTUIqAng==,type:str]
        defaultPodOptions:
            annotations:
                backup.velero.io/backup-volumes: ENC[AES256_GCM,data:IuJO8QMf,iv:WjhSCBZ9+087dGcEx3aTbw+Uj6MrraYoGhhHQ61kQ3I=,tag:lYQD26+Z8ywMiw2ParZbkA==,type:str]
        service:
            app:
                controller: ENC[AES256_GCM,data:xxJSABDUOOI=,iv:VYPbaEPKREoSIqeBYKdrl4sjUGHWZETLjNObNgtBIaI=,tag:hkO7UVMGJF1oUaR+nklMYg==,type:str]
                ports:
                    http:
                        port: ENC[AES256_GCM,data:I7w+HQ==,iv:N2LA909d++2gHCa8+exq8U0uPe2BKM6b0hjKBYkFtBs=,tag:KDbcyJDzlIcxLQwC0wSByA==,type:int]
        ingress:
            app:
                enabled: ENC[AES256_GCM,data:NF+HFQ==,iv:fKbTmmjzK8pkwagOdObZtAeBPwDJlRvEIjm2HcfuoKw=,tag:BHuQUsZMi2bge5cLejHICw==,type:bool]
                className: ENC[AES256_GCM,data:N8vcDCdFAtk8ttojy3g=,iv:Kg6D74ixGPhOh5YWjuFCrL+7ASy9IgeS+SD+dYKKDTc=,tag:sJq0yokMfPiMmupqcJTjcw==,type:str]
                hosts:
                    - host: ENC[AES256_GCM,data:WJROi4KN4BI9baGRQx0Pv3lnrvjSqDoRfyE=,iv:Nn2lQEWJyt14avwiYojL8PqHAxSfpBaafNvd5+F7WN0=,tag:CDCGiXNYY8120hKIH8j2hA==,type:str]
                      paths:
                        - path: ENC[AES256_GCM,data:nQ==,iv:IjgqR1cz3yqC99tKc6LaCzxMscoptnDlRxkfXfq9dmA=,tag:zcbRJq8H7hGIbLCe9go79w==,type:str]
                          service:
                            identifier: ENC[AES256_GCM,data:mVxf,iv:u3a2N8ec9d5tUPJ97DovCueMyrohJdXAGTw/G/B7sOg=,tag:UubUEqpcTGjtbwANQo+5tw==,type:str]
                            port: ENC[AES256_GCM,data:tjwxFg==,iv:4rBFicIBnCzwCxWtdn4jr8LEpg4nwB74BBKxay1vDOE=,tag:u4krgHmHYKWIvQ2CSbg5fA==,type:int]
                tls:
                    - secretName: ENC[AES256_GCM,data:sx6f2PA82BEIsHHrrqw7rXMnPGseWQ==,iv:oY7POsLb8KjUwOiUgl0gDf1Yiw+D73dH+Q0RwNMHhO0=,tag:s3Xd39RyG03Qiteo0rFCJA==,type:str]
                      hosts:
                        - ENC[AES256_GCM,data:u8Ea5IkAF+f/tiymnhuRoMml4f4xbVLBnUw=,iv:c0aq52dHoYxPF2RJ6COHU44W3QwCmR4hTXZJ7p2HgW8=,tag:dlEMcxi2U6lE32mHP11PTw==,type:str]
        persistence:
            config:
                accessMode: ENC[AES256_GCM,data:UxQasY85bMBDdF5hpQ==,iv:2BB0dBlmdFdiQog4GujtDN6SCHpJbOxjD88HaOctR+k=,tag:atsWzo7kujeKf5/hv3Q3Dw==,type:str]
                size: ENC[AES256_GCM,data:L2S+pIY=,iv:ksAOj7ItbZosIF7hgmBCdJxBUhio0Oj3/psdak7GoCI=,tag:rqp/W+ZmuaU33rCJ8Ar7Eg==,type:str]
            logs:
                type: ENC[AES256_GCM,data:63kKXDNwWWQ=,iv:4v0HRLUzStVkXb8GJXwaCIVM2DncV7F+ife+4MAgOFw=,tag:n4R/mIQ64SXKk+nVc6zBVQ==,type:str]
                globalMounts:
                    - path: ENC[AES256_GCM,data:cM5PBu/7dReykki3,iv:Es9+cp2XJkjTeIuu98Vgkd8xzO/6LIrNWSFcMc2EBsY=,tag:VbGKujNq5BPVbWv/NqAR7A==,type:str]
            media:
                type: ENC[AES256_GCM,data:MwW+,iv:jKhI89gcANCG925R7cYBFFHjnKOZhmA3azY6Y4729do=,tag:+7Tc9lgAYnrKhgU1itNCPw==,type:str]
                server: ENC[AES256_GCM,data:B/vhPoZpZos=,iv:Dzl3z8VkOXnzHAAtBWsXbC0hEaXtpSqnw03Vr30AcrY=,tag:rxBOsmhOoLTcJ3R4YOTPaA==,type:str]
                path: ENC[AES256_GCM,data:gqUaozpgcrI4FNNu2QaV,iv:nTwM6yjlvLo/jTL9ruU4zFYRiafO4xKMwOFEa9Ny3c4=,tag:tABECiPdLw81w4Vuq/Wc2g==,type:str]
                globalMounts:
                    - path: ENC[AES256_GCM,data:zQSMx0g=,iv:cxZbi9KhOyV2S8zGR/kqHZ+aJaXDPkbTzYG9dAM0osw=,tag:OQ2KrzdFL/7K1U5/JULBeg==,type:str]
sops:
    age:
        - recipient: age1umudqfh963mmhgkgatylwh9jgez7qh4twpaqy3ea3nlcarhm09hq5er32r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDa2hEZ2ZjeUF6VjBEUU83
            UGVEZmVLNWZwYmExVEVKdUV2cU91bnVIUlZNCkc2Z0srT2xRY2I1VHhEVjJteEZ2
            M092WHg0SEFQd1IvN0dIZEhPRVFoRWsKLS0tIFc0ci9kcnF3RGpLT2RORGRPdnJD
            YlZ0ZDdvcmI5QzNheEFKdk5pQWtHZncK3P2+vWqQooaU4WWMKw7nGtcnU2zL8N4h
            B1gtAPhr261+YSOvNEug2+wFACulyT/1MZ+dR14xJm+7PmpnMMF3Lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-11T04:25:00Z"
    mac: ENC[AES256_GCM,data:vS6bgqt0u3g11iM/tW54I/C+EG9S3JQu1snpjSXQSj7V2XdMtbGh9EPE/8u7xX/lbXxBGgJ4chA/YWH8rAHpvOhmb74VN/OSTVr5QDaGJ4Qpet7l9PnlongHDgfDyxwKbsdyebbvf6fxYmeh4gr/8Bxsr5lWz1Xc1veucizd87Q=,iv:Abjpf3zrD7HV9XQY0jSVB7hdakl0nrWXiKMhxLsSYwI=,tag:rH8Tm4h+zb6qp7jLSyFKLw==,type:str]
    encrypted_regex: (metadata|values)
    version: 3.10.2
