#ENC[AES256_GCM,data:ZzLKBXJN1jfmgIu5nuRH1dAzbyKekSR0QY5ppY0Zyqrp2zt4YI9G6KnL01kztZCv39aqViQvN8dTvZUxPjj6UlIwboZ/XfqSLoAmxUKbbB07qtOmMpCm7IK+Sp849oEb/5/IlCj+pTSj7E/UYg4YLyqkvUHNcnePLOCMEgMBK1i4NcX5YYg2yKZOTSc+QNMliPwf+y6fsaYn,iv:Cm6ek6f0OjypHgiidoppKO5KZjJrOviWhWVid1BZ0ao=,tag:2F2EDuD6CxflYqBXWoYYIQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:a19p/Hm0TgBdgS5dCSDgqHd91hdQREx4kA==,iv:lfg6ePLwkZksC8AzaMdOmeRQaJD4LtqP4mxhZeIFdnY=,tag:AvUA0eyaeoxZqAo+IeXdhw==,type:str]
kind: ENC[AES256_GCM,data:YmVfNmysEwoNkGo=,iv:yg1XHpror237QZ6JkDBbfFXO1uDsPiUardcRydgJrB8=,tag:KIzmLSXbpqvj31MCwpR6sQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:npu2lcp2NV0=,iv:OgEh7BrrkFuTZDaR4AxcIhtZR/Ne6pZFuByU8ci2YbU=,tag:hGIlBtbyQwiHDwT9Gof0CA==,type:str]
    namespace: ENC[AES256_GCM,data:yJcLn2fiiohvsVcT9ks=,iv:Am6dJeDF8aTyOjx5fjALlayrDrm6mOAljCS+QGuvL/M=,tag:sK9lG9SqBSIifmJD1rAjOw==,type:str]
spec:
    interval: ENC[AES256_GCM,data:TuQ=,iv:qPH+qw41+HpsZ95szeNBNlz6BKGPzhc9t0hnfQvNP7s=,tag:k7ei+J20H35XesW+l0MdFQ==,type:str]
    install:
        createNamespace: ENC[AES256_GCM,data:9wQCyA==,iv:y24upmRyVy7ewc1nGcRNF5TW0W35V2FPcI4hwtBeonY=,tag:JhZEOBQsjX6ZKdh0bqmn6w==,type:bool]
        crds: ENC[AES256_GCM,data:/Lc8usV7O/m97eoIUg==,iv:4YKPWWsa064/aPLBiyv1Cw2iC9lY9pKQNDiN6HtEhWw=,tag:KscWpeovsIkuLXUIl1u5HQ==,type:str]
        remediation:
            retries: ENC[AES256_GCM,data:lA==,iv:LzCRsz54/p58rBoJ25zxPu6LGT3BQZ7ff0X1/FPJ72E=,tag:edaSyyIaZX+L6Elfg5eogA==,type:int]
    upgrade:
        crds: ENC[AES256_GCM,data:WnhI2GyR4Vgp4Ys17A==,iv:mOAa8Q7IiWOvzKCa7GOMMphOrVksO95DJ+35eFtCoTg=,tag:K7ByOKjz5tARsAnX/TRo3Q==,type:str]
        remediation:
            retries: ENC[AES256_GCM,data:CQ==,iv:0pjfB1sgDf7sap8nz6IFviAwdCMTzBs78XwdRSQN2lM=,tag:vnSQSPpElgSkQJZokvmbKw==,type:int]
    chart:
        spec:
            chart: ENC[AES256_GCM,data:oufBXCb3Inmq59+R,iv:KxKmCGSaTZO1ScJJGOLNm5i6Snuo1gzCJsBh1QGBhh8=,tag:bWL2fpBYJmvVixe6JIiglg==,type:str]
            version: ENC[AES256_GCM,data:sw8fQk0=,iv:cGRU4ZrllY9i7+aobdqGHmJIQpWrQxEbCunWlyIEOPA=,tag:bicLo6F3MOf3nTpyGCf2ig==,type:str]
            interval: ENC[AES256_GCM,data:NjY=,iv:sJ5kD3h8ea3VGqMcn3JlCWXu52y86PqNpjNBqm9KLmM=,tag:I7JkUyrH5a4Ki8Lm9IPc9g==,type:str]
            sourceRef:
                kind: ENC[AES256_GCM,data:zWjhAlhqP9iJHoajqzg=,iv:hi5i+Nd+YGy9ZuVJvJxM2OGyMk6GexwBxfHbWZLrYns=,tag:IdY/0tvHwecjGkU/V12HpQ==,type:str]
                name: ENC[AES256_GCM,data:ewVzCzE=,iv:k9xy9g48mcFiQv8Smj7CSZFaDJp4lFqvneNCGugXCpk=,tag:RO5Q7NdDz/aaHmvH+7mgHw==,type:str]
                namespace: ENC[AES256_GCM,data:R5jByCQw00C3b6c=,iv:SzyVQXB1f2gJF0uVx5s8HOx1Gjj3cOvpu7picj/znT8=,tag:k4ckcY4E3/5NfBIyVoZ7TA==,type:str]
    values:
        controllers:
            whisparr:
                strategy: ENC[AES256_GCM,data:Q6XrGSrWW6w=,iv:krefAOZ5Pd7vX9IFyC8jsHTYjPXCPUqMj+6WUgvlAhs=,tag:iRDH/7//aE3mDYnGWXTJrQ==,type:str]
                containers:
                    app:
                        image:
                            repository: ENC[AES256_GCM,data:JKT7pubWt5oCw/q/dZ0IETEWu81WlQ==,iv:hzmBElkNd4xMooROeEA9jRE4AAfsRIAE94CmLQia9tU=,tag:YaHvM4nkxyXkq0xzDnir1A==,type:str]
                            tag: ENC[AES256_GCM,data:eZ8=,iv:+ELMY8G0iMmt5eq/GECgr8lTixFUlnCGMFZqOKvF7v4=,tag:7PoXOMp8OPzupwp1Ef8QoQ==,type:str]
                            pullPolicy: ENC[AES256_GCM,data:dEndvt7X,iv:imvZMP/Fj6xGkim3ZRnM7G5Nwdao55+77mnv7bCKMwo=,tag:3idbQMSp5dFSe+MUfdeaiA==,type:str]
                        env:
                            TZ: ENC[AES256_GCM,data:vCLcBFTxokr7aelLOkMgZzKBwg==,iv:d4Jow1QrY3RBpZvtLLiyDtpITyMbFGon5Is+uOxGD6g=,tag:NB+akLN0z4FbV8ypydYDMg==,type:str]
                            PUID: ENC[AES256_GCM,data:3No3nw==,iv:BYAB0w2BMWZcB9Yxj17cEt1b0844NPDLka9nnwdVUvE=,tag:y0LUjjjP4v8MpND72aoMXQ==,type:int]
                            GUID: ENC[AES256_GCM,data:jnybCQ==,iv:RGL7GnHoMDuUAiaYPDSqv2jHTWgwnIwbG+b9Xwr3pwk=,tag:+gD9+ikzXAgDmQPeQjEd8g==,type:int]
                        probes:
                            liveness:
                                enabled: ENC[AES256_GCM,data:NLOrRg==,iv:ucPeUjfSkGrSFbCXE4cYAessuiwHo8CuWEbM9GvscJ4=,tag:wCqGaqzFPzfwmDLRECOjaA==,type:bool]
                                custom: ENC[AES256_GCM,data:X43cuw==,iv:QmTJKXp384QntaEoWaJ1nKaf7pVaODfd78elBhptGyo=,tag:QBjuC+uH+FQT5ERpb2Z5Yg==,type:bool]
                                spec:
                                    httpGet:
                                        path: ENC[AES256_GCM,data:xTOrqwU=,iv:sEuQhiXtp1X7wxCDmyvIrlsiygRkenXQTc8LeQbvtMI=,tag:gKaygRl9v8t+JL8qkiOL/w==,type:str]
                                        port: ENC[AES256_GCM,data:lsvohg==,iv:AZ4EN28TFCDX23N34kknlAK1iSKBdsewwgNQItZRCPU=,tag:5nzqwnbE/Hfi6m2jvws7Ug==,type:int]
                            readiness:
                                enabled: ENC[AES256_GCM,data:i+XwZw==,iv:reJRu+271u7RwCMONrevz7D+R7ZcouTFP1tnfi/URD4=,tag:T1fejP25k9shvoehOIA2og==,type:bool]
                                custom: ENC[AES256_GCM,data:f1/KyA==,iv:aZimVeMYoexmoaa1yzlaes/Yjw35COS+1s5C6jg3kwo=,tag:AYmciFKclolyIwsLdnOT5A==,type:bool]
                                spec:
                                    httpGet:
                                        path: ENC[AES256_GCM,data:uXav9oA=,iv:zaPMIXrw8YwEpWnRh9s0zuDx/bvx085Th2WMYQDi6Is=,tag:XT5amzfNy3PRsGLFzQjjlA==,type:str]
                                        port: ENC[AES256_GCM,data:SMSSVg==,iv:qUlX/YKjpFO2bEtUUn0z261FZPQfPJcE8TdRMZGDr0c=,tag:EhASMYF/mNqaN2HzUhQW5w==,type:int]
                        resources:
                            requests:
                                cpu: ENC[AES256_GCM,data:sBHG2A==,iv:vBvDV+7hF0sN0N1LghhRcoI6Ec4fYkVAWIvALIF3IOM=,tag:RffFLRhyNZoY1y7Y4g0yPA==,type:str]
                                memory: ENC[AES256_GCM,data:5+mTsIk=,iv:ez1Iqd9PPptlIDJY5q7TdO9p4rH3H0vctUfM7nARfi4=,tag:PQzUGl6mtgMK7b+xWfnReA==,type:str]
        defaultPodOptions:
            annotations:
                backup.velero.io/backup-volumes: ENC[AES256_GCM,data:Pz2mMwQr,iv:YbEUvAtsOhawS5mfyMpnWe62QQi5AhTk6t/hcr6Et3U=,tag:n3raPK7MLxCzzOJe488rfg==,type:str]
        service:
            app:
                controller: ENC[AES256_GCM,data:4RZLXHIEdbQ=,iv:DERcvn0HFc6dQleXGlaG82YI09U5e3T3kKaA4S7epLg=,tag:7kEDDH0OFNHOTCzP1+jS3w==,type:str]
                ports:
                    http:
                        port: ENC[AES256_GCM,data:N9RsrQ==,iv:cY9dudIgwAdJrXN6QgD0AFKiGiZhB0fYaOYQjCrcIzk=,tag:ndoekmlpEtmAmkqsyOKBuw==,type:int]
        ingress:
            app:
                enabled: ENC[AES256_GCM,data:U6etBA==,iv:kcoyhhyP8pVEEFRiakQw5tjSvtJ+fZrvLMH0NQbpgs0=,tag:goeDdDD0RcWgiJN23XCU5A==,type:bool]
                className: ENC[AES256_GCM,data:Kgw/pfOvCLYadcfUEVs=,iv:xgwkRqiB5b20gzTE9ReDbDzv6hm52Fh6E5CtYDmDOBU=,tag:uDyTUUdUpP+kCeiVhEeVBQ==,type:str]
                hosts:
                    - host: ENC[AES256_GCM,data:sw62aiT0xkIK7IID1vcs7kmU97vcOVSlh5I=,iv:G+Np9siLxnx1AELxORqXYG9qokXeSV8LfioGcKv860g=,tag:tSFK0FNDBWGvhAmUNugkZw==,type:str]
                      paths:
                        - path: ENC[AES256_GCM,data:SQ==,iv:70xPiyUjPkqAT3XDtIUty7Z1LLbqxaHPQEbfJHXcxZU=,tag:hCnTeZ/nWaB+vNlmuVwGww==,type:str]
                          service:
                            identifier: ENC[AES256_GCM,data:yYa7,iv:hh4us8s5asrdGcwOtNAtfvdAljMowCvWJAZYnOH6hjI=,tag:p3vNGkYYLYjOMvd9nh53BA==,type:str]
                            port: ENC[AES256_GCM,data:muEjAg==,iv:c+q0DZDqPO41dtfa0D/+oVn+EAkPGG5WlUba4caOPIw=,tag:P15JVLl7Wb/QhReC+XqSzQ==,type:int]
                tls:
                    - secretName: ENC[AES256_GCM,data:BmLsFJil/N3uM8SqlPUxv2yBFoCQwA==,iv:XFbOkumGsuimT0U+NXXusxSsYd+f8JjKKMSX3TXio+Q=,tag:VLCdAxY5zWCygRJ819cF3w==,type:str]
                      hosts:
                        - ENC[AES256_GCM,data:cpwBB1ecpGPfeSROjyRFnNszL6+LTVbB7t4=,iv:a9cGA4GxOA1O1zLwIZi2gGRCVddWg3KkHOYmd/vT3Rc=,tag:utDyCwEaSYKeIl2zzHOCTw==,type:str]
        persistence:
            config:
                enabled: ENC[AES256_GCM,data:Wgfr3w==,iv:jFLx+7ghzfXQ1klzu1kzVWxIWc1wVztN0zPsctZ5iBY=,tag:NRiS/hmIfgJdxBzymGK2Gw==,type:bool]
                retain: ENC[AES256_GCM,data:890yjQ==,iv:uXXXG15OpI6s1QqnYCZbvSsCKoEWHYESxNgENL38Onw=,tag:P4wduEbhf53vswIOkFHtWQ==,type:bool]
                globalMounts:
                    - path: ENC[AES256_GCM,data:6jtfIULYhQ==,iv:8YRiMtoTAwGiOVLMa6vpIevBRjP4lsSp/MAL0LYDY2g=,tag:cWmuGlHx4YRr/qd1oP+Jaw==,type:str]
                accessMode: ENC[AES256_GCM,data:lbbXmCRde3G3uu2xZg==,iv:7AWit+V0sFIKXmQzJiFGyDv9axMv7TT1rC7BqfU/0tQ=,tag:vmUiRyvEmKZbe43Ncc7cBw==,type:str]
                size: ENC[AES256_GCM,data:0K/clX4=,iv:vDq1nnRTpLyibRzVPHASYpwFqYS28VaNDrMacl/WJcg=,tag:7FVMWdeZx8yZHzBLAclNTw==,type:str]
            logs:
                type: ENC[AES256_GCM,data:1+2pV7h7cOM=,iv:u44pCpUaJP4vSFVFrRR/X9N2X3geE3QLEzqES//5B48=,tag:WVCf24nq35UZDonjEA6JZw==,type:str]
                globalMounts:
                    - path: ENC[AES256_GCM,data:9MnTkeU5wJLIANS1,iv:sFRY5R7lthXuX3ZVKMNvJRpCDJxmYO8pigTbRgDHZIg=,tag:jgRcyNGB/nMNHFDorW3GJA==,type:str]
            media:
                type: ENC[AES256_GCM,data:c2Y2,iv:NKIbD6LavVFJadUvSFusmMNkLj38zEuUr/T6JIosvoQ=,tag:Q+MpvnKQoN+oZ/CywHYCfg==,type:str]
                server: ENC[AES256_GCM,data:AgFmqWcP30A=,iv:WUMej5Xjoma+kLg7MvXAMSD4WakSpCi0UGMWXlSeozo=,tag:F4pVD/aepVXKZw+Hmv+pCw==,type:str]
                path: ENC[AES256_GCM,data:Ux6KIbKoiJdLv+xKhXjE,iv:t6WxHcTyY4FCkTlOIstN5uZGKsWpqa+OT3ZqrZjkqjA=,tag:BS14n+nxDPKHJr1of+9d+w==,type:str]
                globalMounts:
                    - path: ENC[AES256_GCM,data:N5mlTqY=,iv:0C1Z/2YbxXl9lYUMOsam6kmUwHX29t3YIB29/VjO/A0=,tag:3ZgjK1KuNsHMTXfRVDK/UA==,type:str]
sops:
    age:
        - recipient: age1umudqfh963mmhgkgatylwh9jgez7qh4twpaqy3ea3nlcarhm09hq5er32r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQlZ2V0gzQlNjM3ZZT2Np
            ZS9OL1dOYW55NTFxYXdPVWVwL3JWSlEwOEhFCmFaL3k4cUhlRGpJRHNpYTNyTXVK
            QlFieGZraVkrM1NUK3dtdXJ6ZVd2TzgKLS0tIGlPWE10cmNHVGhrRkhxSURFbzRC
            TllYTHZMZGxzd0ZMd2pQbUFJYUtmNjAKMGzw7srm4tPwZdpKh8aRX/Qqb02VVpDF
            EiFgrXY+9G8S84uS5Hg7O0sibwpfvu188UYqRx35Btf0leV2Glwa1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-04T23:55:34Z"
    mac: ENC[AES256_GCM,data:egYG/ToIQY/FQ4qxMmzuZtnWR/IlFUiC855UnK08yrUTzvTWQ97yu1F+3e0uZhl06Qndyg1z2k+gfF+C3e22v1vxuYiInK4sZYMCInJ13/ATHy2wCdNYP9tXU01We48HaCxjigYpnp2dT129Ciag5gRquUkUe4HVuOBvKyQcyok=,iv:0/rvwEccGmsaXHSC9/asKUvi1nj0pW+Ob1fgrDVnv/I=,tag:kmttRWobSmtVKfugaboGAw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
