apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media-managers
resources:
  - helm-release.yaml
  - secret.sops.yaml
configMapGenerator:
  - name: kometa-configmap
    files:
      - config.yml=./resources/config.yml
      - playlists.yml=./resources/playlists.yml
generatorOptions:
  disableNameSuffixHash: true
