apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app portainer
  namespace: *app
spec:
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: portainer
      version: 1.0.66
      sourceRef:
        kind: HelmRepository
        name: portainer-repo
        namespace: flux-system
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Deployment
              name: portainer
            patch: |
              - op: add
                path: /spec/template/spec/priorityClassName
                value: keep-alive
              - op: add
                path: /spec/template/metadata/annotations
                value:
                  backup.velero.io/backup-volumes: data
  values:
    image:
      repository: portainer/portainer-ee
      tag: 2.30.1
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
    service:
      type: ClusterIP
    tls:
      force: true
    ingress:
      enabled: true
      ingressClassName: internal-nginx
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Container Management Simplified
        gethomepage.dev/group: Infrastructure Management
        gethomepage.dev/icon: *app
        gethomepage.dev/name: Portainer
        gethomepage.dev/namespace: *app
        gethomepage.dev/app: *app
        gethomepage.dev/href: https://portainer.k8s.hyde.services
      hosts:
        - host: &host portainer.k8s.hyde.services
          paths:
            - path: /
              pathType: ImplementationSpecific
              port: 9443
      tls:
        - hosts:
            - *host
          secretName: wildcard.hyde.services
    persistence:
      size: 128Mi
