---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portainer
  namespace: portainer
spec:
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: portainer
      version: 1.0.61
      sourceRef:
        kind: HelmRepository
        name: portainer-repo
        namespace: flux-system
  values:
    image:
      repository: portainer/portainer-ee
      tag: 2.27.2
    nodeSelector:
      kubernetes.io/hostname: "nebula"
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
    service:
      type: ClusterIP
    tls:
      force: true
    ingress:
      enabled: true
      ingressClassName: internal-nginx
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Container Management Simplified
        gethomepage.dev/group: Infrastructure Management
        gethomepage.dev/icon: portainer
        gethomepage.dev/name: Portainer
        gethomepage.dev/namespace: portainer
        gethomepage.dev/app: portainer
        gethomepage.dev/href: https://portainer.k8s.hyde.services
      hosts:
        - host: portainer.k8s.hyde.services
          paths:
            - path: /
              pathType: ImplementationSpecific
              port: 9443
      tls:
        - hosts:
            - portainer.k8s.hyde.services
          secretName: wildcard.hyde.services
    persistence:
      size: 128Mi
