apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: nextcloud
      version: 6.6.9
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  values:
    image:
      repository: nextcloud
      tag: 31.0.2-fpm-alpine
    nginx:
      enabled: true
      config:
        headers:
          "Strict-Transport-Security": "max-age=15768000; includeSubDomains;"
  valuesFrom:
    - kind: Secret
      name: nextcloud-values
