---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  install:
    createNamespace: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: ingress-nginx
      version: 4.12.3
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    installCRDs: true
    controller:
      kind: DaemonSet
      ingressClassResource:
        name: internal-nginx
        controllerValue: "k8s.io/ingress-internal"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      service:
        loadBalancerIP: 192.168.4.10
        externalTrafficPolicy: Local
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "10254"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx-external
  namespace: ingress-nginx
spec:
  interval: 5m
  install:
    createNamespace: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: ingress-nginx
      version: 4.12.3
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    installCRDs: true
    controller:
      kind: DaemonSet
      ingressClassResource:
        name: external-nginx
        controllerValue: "k8s.io/ingress-external"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      service:
        loadBalancerIP: 192.168.4.15
        externalTrafficPolicy: Local
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "10254"
