apiVersion: v1
kind: Secret
metadata:
    name: notifiarr-secrets
    namespace: media-managers
data:
    machine-id: ENC[AES256_GCM,data:jbMk52hq/Wa8j2ZPguQaklra0oWtDU/lZD8R5Jf5ckJfXHTva8voEBol7Ic=,iv:XWLuYPsCqg3ily5JdCO1Lnjc2rhdRoXmYPDnergXXEY=,tag:vBK8dPZuD8I30gc7phfZqA==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1umudqfh963mmhgkgatylwh9jgez7qh4twpaqy3ea3nlcarhm09hq5er32r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMFd4UDcvSE1EZHFpdGJv
            cHN0dlZzcHNUN284MHErS0o2TXVBNFlxK2pvCkkzY2V2NHRYT3UxUlpEdGt5N1I2
            V3Evd0R1ZWJselVBc1lOWitxcjZVYWsKLS0tIFM1dkZtWHA3aGtkS05FOGgyMld0
            ZitEalVIL3Nra0Jnck5LR2R5dG1iSW8KnIogk7hX1gmOl+5ITd5H72jzEEO6dDe9
            TiUaJ37MV9zCNbCS6m7mkWDxaxM7qzfZ5FhoS7q8IpfUTRrrn+KSsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-07T01:17:20Z"
    mac: ENC[AES256_GCM,data:G/HBq8UqDIpNVto+1LhGFjnQ9M4LzpSs7spqHWntzLbnh4m8XNw6H3ekwS7z9z54EK4NzlinVQB98UVwHse64xVv9cvkd4cFDh8Ph/icMFjJL23cJWGpRdkDpuSud7x8YTeRFnvd9mWoFaBT9PjecDGPv/3az6R0umMPMdemdQc=,iv:hd9fFuRjYbuwcmyV8CqbKeFOz7bHJhpJBsNRASq6yjM=,tag:WqW3Gum8v1pueUbkAHiY6A==,type:str]
    encrypted_regex: ^(data|stringData|annotations|)$
    version: 3.10.2
