apiVersion: v1
kind: Secret
metadata:
    name: notifiarr-secrets
    namespace: media-managers
data:
    machine-id: ENC[AES256_GCM,data:jbMk52hq/Wa8j2ZPguQaklra0oWtDU/lZD8R5Jf5ckJfXHTva8voEBol7Ic=,iv:XWLuYPsCqg3ily5JdCO1Lnjc2rhdRoXmYPDnergXXEY=,tag:vBK8dPZuD8I30gc7phfZqA==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1umudqfh963mmhgkgatylwh9jgez7qh4twpaqy3ea3nlcarhm09hq5er32r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMFd4UDcvSE1EZHFpdGJv
            cHN0dlZzcHNUN284MHErS0o2TXVBNFlxK2pvCkkzY2V2NHRYT3UxUlpEdGt5N1I2
            V3Evd0R1ZWJselVBc1lOWitxcjZVYWsKLS0tIFM1dkZtWHA3aGtkS05FOGgyMld0
            ZitEalVIL3Nra0Jnck5LR2R5dG1iSW8KnIogk7hX1gmOl+5ITd5H72jzEEO6dDe9
            TiUaJ37MV9zCNbCS6m7mkWDxaxM7qzfZ5FhoS7q8IpfUTRrrn+KSsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-07T08:18:30Z"
    mac: ENC[AES256_GCM,data:91sZA6/6Q/Z4Dg7xqwHz5+ydY5JIJw9TlEZva9My/DBAZ0PBbTFaKtw1q5lzBbqJ2IygTrngQy8pj01iZ59/wvbCTdJkcYypir8HsaJXr7bBA4sdoU6VhtCm6+DFnED66ba+bWgpF9mGc2QaEigP+5Tiz/fT+MLb0plWKnky9AI=,iv:TjfDHmGOVl0KCEF2oRK4SI+8grgZIpcqj5+Ng37Xw4M=,tag:1rirHH9VSiyLlXAXwiDjIg==,type:str]
    encrypted_regex: ^(data|stringData|annotations|)$
    version: 3.10.1
---
apiVersion: v1
kind: Secret
metadata:
    name: ghcr-credentials
    namespace: media-managers
data:
    .dockerconfigjson: ENC[AES256_GCM,data:HGwXdI1kOV/8nlMTyzsMIMA6bX2Eia7ToOF/naxxsZC22e48kJIXxUOcxeqHud6SQArVOotMOOpf2zEzeMQw3jca5dlZZScP4HnI/ZP8beU9O/gt4t9hfi4G8qWRQ52DVNYpnmHiEDEWvrS1652pZ338c5slwczYgBLFFNL/ietVLmAms0PsdsX62XhnZw/w,iv:+9mZoCKpA6leyMTPa4KipSkEPb8tC08WEL8JI81IWA0=,tag:UTuIkZPPehMDXYTrhrXLEg==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1umudqfh963mmhgkgatylwh9jgez7qh4twpaqy3ea3nlcarhm09hq5er32r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMFd4UDcvSE1EZHFpdGJv
            cHN0dlZzcHNUN284MHErS0o2TXVBNFlxK2pvCkkzY2V2NHRYT3UxUlpEdGt5N1I2
            V3Evd0R1ZWJselVBc1lOWitxcjZVYWsKLS0tIFM1dkZtWHA3aGtkS05FOGgyMld0
            ZitEalVIL3Nra0Jnck5LR2R5dG1iSW8KnIogk7hX1gmOl+5ITd5H72jzEEO6dDe9
            TiUaJ37MV9zCNbCS6m7mkWDxaxM7qzfZ5FhoS7q8IpfUTRrrn+KSsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-07T08:18:30Z"
    mac: ENC[AES256_GCM,data:91sZA6/6Q/Z4Dg7xqwHz5+ydY5JIJw9TlEZva9My/DBAZ0PBbTFaKtw1q5lzBbqJ2IygTrngQy8pj01iZ59/wvbCTdJkcYypir8HsaJXr7bBA4sdoU6VhtCm6+DFnED66ba+bWgpF9mGc2QaEigP+5Tiz/fT+MLb0plWKnky9AI=,iv:TjfDHmGOVl0KCEF2oRK4SI+8grgZIpcqj5+Ng37Xw4M=,tag:1rirHH9VSiyLlXAXwiDjIg==,type:str]
    encrypted_regex: ^(data|stringData|annotations|)$
    version: 3.10.1
