---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crowdsec
  namespace: crowdsec
spec:
  interval: 5m
  install:
    createNamespace: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: crowdsec
      version: 0.19.1
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: crowdsec
        namespace: flux-system
  values:
    container_runtime: containerd
    agent:
      acquisition:
        - namespace: ingress-nginx
          podName: ingress-nginx-external-controller-*
          program: nginx
          poll_without_inotify: true
      env:
        - name: COLLECTIONS
          value: "crowdsecurity/nginx"
    lapi:
      env:
        - name: ENROLL_KEY
          valueFrom:
            secretKeyRef:
              name: crowdsec-secrets
              key: enroll-key
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: crowdsec-secrets
              key: db-password
        - name: ENROLL_INSTANCE_NAME
          value: "k8s-homelab"
        - name: ENROLL_TAGS
          value: "k8s linux"
        - name: BOUNCER_KEY_nginx
          valueFrom:
            secretKeyRef:
              name: crowdsec-bouncers
              key: nginx
      persistentVolume:
        config:
          enabled: false
        data:
          enabled: false
    appsec:
      enabled: false

    config:
      config.yaml.local: |
        db_config:
          type: mysql
          user: crowdsec
          password: ${DB_PASSWORD}
          db_name: crowdsec
          host: mariadb.database.svc.cluster.local
          port: 3306

        api:
          server:
            auto_registration:
              enabled: true
              token: "${REGISTRATION_TOKEN}" # /!\ Do not modify this variable (auto-generated and handled by the chart)
              allowed_ranges:
                - "127.0.0.1/32"
                - "10.0.0.0/8"
