apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-custom-css
  namespace: authentik
data:
  custom.css: |
    /*** global ***/
    :root {
      --ak-accent: #3a244a;
      --pf-global--primary-color--100: #70468e;
      --pf-global--primary-color--200: #55356c;
      --pf-global--primary-color--400: var(--ak-accent);
    }

    .pf-c-login__main,
    .pf-c-login__main::before {
      border-radius: 8px;
    }

    /*** hide footer ***/
    ul.pf-c-list.pf-m-inline {
      display: none !important;
    }
