apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-external-controller
  namespace: ingress-nginx
data:
  strict-validate-path-type: "false"
  allow-snippet-annotations: "true"
  annotations-risk-level: "Critical"
  enable-real-ip: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
data:
  strict-validate-path-type: "false"
  allow-snippet-annotations: "true"
  annotations-risk-level: "Critical"
