# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app paperless-ai
  namespace: paperless-ngx
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: app-template
      version: 4.1.1
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      paperless-ai:
        strategy: Recreate
        containers:
          app:
            image:
              repository: clusterzx/paperless-ai
              tag: 3.0.4
            env:
              ADD_AI_PROCESSED_TAG: "no"
              AI_PROCESSED_TAG_NAME: ai-processed
              AI_PROVIDER: openai
              DISABLE_AUTOMATIC_PROCESSING: "no"
              OPENAI_MODEL: gpt-4o-mini
              PAPERLESS_AI_PORT: "3000"
              PAPERLESS_API_URL: http://paperless-ngx:8000/api
              PAPERLESS_USERNAME: ai
              PROCESS_ONLY_NEW_DOCUMENTS: "yes"
              PROCESS_PREDEFINED_DOCUMENTS: "no"
              SCAN_INTERVAL: "*/30 * * * *"
              USE_EXISTING_DATA: "no"
              USE_PROMPT_TAGS: "no"
            envFrom:
              - secretRef:
                  name: paperless-ai-secrets
            probes:
              liveness: &probe
                enabled: true
              readiness: *probe
              startup: *probe
            resources:
              requests:
                cpu: 500m
                memory: 512Mi
              limits:
                cpu: 700m
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
    defaultPodOptions:
      annotations:
        backup.velero.io/backup-volumes: config
      securityContext:
#        runAsUser: 1001
#        runAsGroup: 1001
#        runAsNonRoot: true
#        fsGroup: 1001
        fsGroupChangePolicy: "OnRootMismatch"
      nodeSelector:
        kubernetes.io/arch: amd64
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 3000
    ingress:
      app:
        enabled: true
        className: internal-nginx
        hosts:
          - host: &host paperless-ai.k8s.hyde.services
            paths:
              - path: /
                service:
                  identifier: app
                  port: *port
        tls:
          - secretName: wildcard.hyde.services
            hosts:
              - *host
    persistence:
      config:
        accessMode: ReadWriteOnce
        size: 128Mi
        globalMounts:
          - path: /app/data
# logs
