apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud
resources:
  - ../../base
patches:
  - target:
      kind: HelmRelease
      name: nextcloud
    patch: |-
      - op: replace
        path: /metadata/name
        value: nextcloud2
      - op: replace
        path: /spec/valuesFrom/0/name
        value: nextcloud2-values
secretGenerator:
  - name: nextcloud2-values
    files:
      - values.yaml=values.sops.yaml
    options:
      disableNameSuffixHash: true
