- name: Manage Kubernetes cluster
  hosts: all:!localhost:!bastion
  become: true
  gather_facts: false
  pre_tasks:
    - name: Set hostname from Ansible inventory
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

- name: Install Kubernetes
  ansible.builtin.import_playbook: kubernetes_sigs.kubespray.cluster
