apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: nextcloud
    namespace: nextcloud
spec:
    interval: 5m
    install:
        createNamespace: true
    chart:
        spec:
            chart: ./Helm/apps/nextcloud
            reconcileStrategy: Revision
            sourceRef:
                kind: GitRepository
                name: flux-system
                namespace: flux-system
    values:
        instances:
            - domain: ENC[AES256_GCM,data:ao/4rH22vWie3q/YLjMLl2h2edfMcQQ=,iv:jgzw0Tj0asLo9vVhH0JJ2J7Uf/HzFsn3hwWiPm+aQ7A=,tag:JJE++l4y4YZ/ZMgvc/jtxQ==,type:str]
              storage: ENC[AES256_GCM,data:AlbI,iv:AjLxQWDHfp9s7Qbenb3a2Yc037afKkvNFlirm/qAzPc=,tag:JNblM/tnPjj0cvu8gDW+9g==,type:str]
              tlssecret: ENC[AES256_GCM,data:IdMgP3tQjvflmTc+SPsS3nj1j1IJHBXL,iv:0hof9KO7nJMWXtPyvTP2HqgvVNwUtF0hMmdNXTx6zwo=,tag:DjuGBVuyXrg+TxSoQhuDGQ==,type:str]
              nfsMounts:
                - source: ENC[AES256_GCM,data:jBcCvTBuxwtYTe1cdlBjkCQ6Z7NfwdSElg==,iv:UNnFkmBr23Hp2tPkABnBEe4x6nsg2G1lHeJk2q8jCaw=,tag:fHM+FEfqTKTAUm/0VFikLA==,type:str]
                  destination: ENC[AES256_GCM,data:4eFKJnKQuAaGkkgZaH8q5zhvgaFAoY+V7A==,iv:Hs3wMitI4Fwm4yqpNYvwLKtwYGIkQkMvl0fCcpUIkAc=,tag:kGAtiE5coz5PPyGXh8roRQ==,type:str]
                - source: ENC[AES256_GCM,data:XaXuZNtgOgIb1oGbW4pTLRFnpcYl11pwGg==,iv:PxbbSBvzQxESea0ER0UF+GC5tcPo3B+d9PmVrVFWh3E=,tag:R2WNk1RrKDvjteNdqmWi3g==,type:str]
                  destination: ENC[AES256_GCM,data:+R4p6VZsfHmLKPR6aTG3stuEUHkmMnAvvQ==,iv:UgpYQQysWx+qCvW0j5VpPrpyKRx8GSCyslO4AEVkBJE=,tag:rwUK9X23deY1nWIe3n3JPQ==,type:str]
                - source: ENC[AES256_GCM,data:HYDM5ZSrWLh4pp94NWGt1Od/xES4qKMZ9i4x,iv:w4kH8rkcxTe49IRgTo3SFiOPriYvxDkJYJNJ/YxiNaY=,tag:jtO0xBzfEZ7Y2ZM+TFu0mQ==,type:str]
                  destination: ENC[AES256_GCM,data:Wy4rAMDzUHrnTUmvpQ==,iv:B/TyhJILJOxjbq6lLzIhRpZitoQhe3GgvgX/yJg7pA8=,tag:v0lx7g+JvOM5JLCGb3X4rA==,type:str]
                - source: ENC[AES256_GCM,data:kJhn+E9n6+h1j33nPxGmDaNMMghA0yHszj4=,iv:ASp2z5U1srB26eNAoWgx3VWH/oxiPsXKRZ/w14IU9fU=,tag:MVH50L1JobDeyruGuaGvtQ==,type:str]
                  destination: ENC[AES256_GCM,data:k4pGgGJ18SKQX6GI,iv:bn4wXORKzQXoLFcd7D2A+mTVBPlHhzPY37FiTHzu3FY=,tag:1tG2NUcart/eaHqdrQaACA==,type:str]
                - source: ENC[AES256_GCM,data:sWHtFG2bE0K6lB9VgWnQtch6LduohWq09A==,iv:uX6V8nogo+/eBwlNJxIg/y892wpcuJ4hJ6uydsFltZg=,tag:Ji3mS4+OU+zer9qLt1eGDg==,type:str]
                  destination: ENC[AES256_GCM,data:J8ZtKNPJqAZoWVc=,iv:ulbSazEgbgx5kd3i5V6jIlTw97gfCxTil69DsGfCmbs=,tag:wlqwVJDoc9fB4G2IAz0TPg==,type:str]
sops:
    age:
        - recipient: age1umudqfh963mmhgkgatylwh9jgez7qh4twpaqy3ea3nlcarhm09hq5er32r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNkgyeGlZZ0laaW96Y3J0
            TWRadHNQRTBleWxPUk92bTdFNW1SNk8vRm04ClliR2RKekJTRitBMGNCTFEzWmFk
            Rk52SVBzRldpUmZIaFRiUU5tY3ZmVU0KLS0tIDBNM2IwTm53Wi9naDBJdnJqQnAz
            dzlpbmNQT1BpajVaOHVORmhjUWxneTQKKJzkGySWulwFAb721Zxmh3w8Gn+MPPpS
            Z3e5k5Vu0MYYyzw/QiLBjVI92/hJJOITAS9Kiy0EJlCSsX77Hd5QEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-07T02:32:21Z"
    mac: ENC[AES256_GCM,data:3fjIHl7b8YURzUIDAZgAIm2IPFLnaeIY9Yf+3t2SluBF3MohUmMyxNiewXZCvEWX9wtZQwwiX8lRoC9hIqBAAszx8mU0/eJY9yFnU9knehZhqclsamlJyroQuvCRAPGsdFi0BQypyS+w+dsMBVo7gZS+kxT8bCojOzZeqyy8j6U=,iv:WiBsdlYhASfV9MHnHVxvEsDAjkBdCfFEEWKvz0s94C0=,tag:gNa7OJuaBG1N0sP8vU/IuA==,type:str]
    encrypted_regex: ^(instances|)$
    version: 3.10.1
