apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-ngx
  namespace: paperless-ngx
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: paperless-ngx
      version: 0.2.8
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: hydaz
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/paperless-ngx/paperless-ngx
      tag: 2.15.2
    paperless:
      secretKey:
        existingSecret:
          name: paperless-ngx-secrets
          key: PAPERLESS_SECRET_KEY
      uid: 1001
      gid: 1001
      timeZone: Australia/Melbourne
      database:
        engine: mariadb
        host: mariadb.database.svc.cluster.local
        existingSecret:
          name: paperless-ngx-secrets
          nameKey: PAPERLESS_DBNAME
          userKey: PAPERLESS_DBUSER
          passwordKey: PAPERLESS_DBPASS
        sslMode: DISABLED
      consume:
        polling:
          enabled: 60
    ingress:
      main:
        enabled: true
        className: internal-nginx
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Digital Document Management for Organizing and Archiving Your Files
          gethomepage.dev/group: Storage & File Management
          gethomepage.dev/icon: paperless-ngx
          gethomepage.dev/name: Paperless-ngx
          gethomepage.dev/namespace: paperless-ngx
          gethomepage.dev/app: paperless-ngx
        hosts:
          - host: paperless.k8s.hyde.services
            paths:
              - path: /
        tls:
          - secretName: wildcard.hyde.services
            hosts:
              - paperless.k8s.hyde.services
    persistence:
      data:
        enabled: true
        accessMode: ReadWriteOnce
        size: 128Mi
      media:
        enabled: true
        type: nfs
        server: 10.0.3.7
        path: /mnt/Fast/Public/Paperless/media
        mountPath: /usr/src/paperless/media
        readOnly: false
      export:
        enabled: true
        type: nfs
        server: 10.0.3.7
        path: /mnt/Fast/Public/Paperless/export
        mountPath: /usr/src/paperless/export
        readOnly: false
      consume:
        enabled: true
        type: nfs
        server: 10.0.3.7
        path: /mnt/Fast/Public/Paperless/consume
        mountPath: /usr/src/paperless/consume
        readOnly: false
    #redis:
    #  enabled: true
    #  fullnameOverride: redis
    #  architecture: standalone
    #  master:
    #    persistence:
    #      enabled: false
    #  auth:
    #    enabled: false
    paperless-ai:
      enabled: true
      fullnameOverride: paperless-ai
      image:
        repository: clusterzx/paperless-ai
        tag: 2.7.6
      paperlessai:
        openai:
          enable: true
          existingSecret: "paperless-ai-secrets"
          model: "gpt-4o-mini"
        paperless:
          existingSecret:
            name: "paperless-ai-secrets"
            apiTokenKey: "PAPERLESS_API_TOKEN"
            usernameKey: "PAPERLESS_USERNAME"
      ingress:
        main:
          enabled: true
          className: internal-nginx
          hosts:
            - host: paperless-ai.k8s.hyde.services
              paths:
                - path: /
          tls:
            - secretName: wildcard.hyde.services
              hosts:
                - paperless-ai.k8s.hyde.services
      persistence:
        data:
          enabled: true
          accessMode: ReadWriteOnce
          size: 128Mi