---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pterodactyl
  namespace: pterodactyl
spec:
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: ./Helm/apps/pterodactyl
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
