apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: minio
      version: 5.4.0
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  values:
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2025-04-22T22-12-26Z
    mode: standalone
    deploymentUpdate:
      type: Recreate
    existingSecret: minio-secrets
    persistence:
      size: 2Gi
    ingress:
      enabled: false
    consoleIngress:
      enabled: true
      ingressClassName: internal-nginx
      path: /
      hosts:
        - minio.k8s.hyde.services
      tls:
        - secretName: wildcard.hyde.services
          hosts:
            - minio.k8s.hyde.services
    podAnnotations:
      backup.velero.io/backup-volumes: export
    resources:
      requests:
        memory: 512Mi
