# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app radarr
  namespace: media-managers
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: app-template
      version: 4.0.1
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      radarr:
        strategy: Recreate
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/radarr
              tag: 5.25.0.10024
            env:
              TZ: Australia/Melbourne
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: &port 7878
              readiness: *probe
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
    defaultPodOptions:
      annotations:
        backup.velero.io/backup-volumes: config
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        runAsNonRoot: true
        fsGroup: 1001
        fsGroupChangePolicy: "OnRootMismatch"
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      app:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: 64m
        className: internal-nginx
        hosts:
          - host: radarr.k8s.hyde.services
            paths:
              - path: /
                service:
                  identifier: app
                  port: *port
        tls:
          - secretName: wildcard.hyde.services
            hosts:
              - radarr.k8s.hyde.services
    persistence:
      config:
        enabled: true
        retain: true
        globalMounts:
          - path: /config
        accessMode: ReadWriteOnce
        size: 256Mi
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
      media:
        type: nfs
        server: 10.0.3.7
        path: /mnt/Slow/Media
        globalMounts:
          - path: /data
