apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app uptime-kuma
  namespace: *app
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: uptime-kuma
      version: 2.21.3
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: dirsigler
        namespace: flux-system
  values:
    image:
      repository: louislam/uptime-kuma
      tag: 1.23.16
    podAnnotations:
      backup.velero.io/backup-volumes: storage
    priorityClassName: keep-alive
    volume:
      size: 1Gi
    ingress:
      enabled: true
      className: external-nginx
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Real-Time Monitoring and Uptime Tracking for Your Services
        gethomepage.dev/group: Web Applications
        gethomepage.dev/icon: *app
        gethomepage.dev/name: Uptime Kuma
        gethomepage.dev/namespace: *app
        gethomepage.dev/app: *app
      hosts:
        - host: &host status.hyde.services
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - *host
          secretName: wildcard.hyde.services
