apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.4.10-192.168.4.100
    - 2404:e80:661b:4::10-2404:e80:661b:4::100
