---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: promtail-position-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.storage.promtail.position }}
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: influxdb-appdata-pvc
#spec:
#  accessModes:
#    - ReadWriteOnce
#  storageClassName: longhorn
#  resources:
#    requests:
#      storage: {{ .Values.storage.influxdb.appdata }}
