apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - limit-egress.yaml
  - memcached.yaml
  - namespace.yaml
  - overlays/livemusicvictoria-com-au
  - overlays/staging
  - overlays/wordpress1
