apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wordpress
resources:
  - app/hca
  - app/lmv
  - app/memcached
  - limit-egress.yaml
  - namespace.yaml
configMapGenerator:
  - name: apache-config
    files:
      - values.yaml=resources/apache.yaml
    options:
      disableNameSuffixHash: true
