apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: memcached
  namespace: wordpress
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: memcached
      version: 7.8.0
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    image:
      repository: bitnami/memcached
      tag: 1.6.38-debian-12-r0
    updateStrategy:
      type: Recreate
      rollingUpdate:
