apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud
resources:
  - helm-release.yaml
  - secret.sops.yaml
secretGenerator:
  - name: shs-values
    files:
      - values.yaml=values.sops.yaml
    options:
      disableNameSuffixHash: true
