---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-system
  namespace: longhorn-system
spec:
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: longhorn
      version: 1.8.1
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: longhorn-system
        namespace: flux-system
  values:
    enablePSP: false
    defaultSettings:
      defaultDataLocality: best-effort
      orphanAutoDeletion: true
    ingress:
      enabled: true
      host: longhorn.k8s.hyde.services
      ingressClassName: internal-nginx
      tls: true
      tlsSecret: wildcard.hyde.services
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Block Storage For Kubernetes
        gethomepage.dev/group: Infrastructure Management
        gethomepage.dev/icon: longhorn
        gethomepage.dev/name: Longhorn
        gethomepage.dev/namespace: longhorn-system
        gethomepage.dev/app: longhorn
        # authentication
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: basic-auth
        nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    longhornUI:
      replicas: 1
      nodeSelector:
        kubernetes.io/hostname: "nebula"
    global:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
