---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adguard-home
  - authentik
#  - crowdsec
  - homepage
  - ingress-nginx
  - media-managers
  - metallb
  - reverse-proxy
  - velero
