apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: adguard-home
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: adguard-home
      version: 0.19.0
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: rm3l
        namespace: flux-system
  values:
    image:
      repository: adguard/adguardhome
      tag: v0.107.59
    strategy:
      type: Recreate
      rollingUpdate:
    services:
      dns:
        type: LoadBalancer
        externalTrafficPolicy: Local
      https:
        enabled: false
      dnsOverTls:
        enabled: false
      dnsOverQuic:
        enabled: false
      dnscrypt:
        enabled: false
    ingresses:
      http:
        enabled: true
        className: internal-nginx
        hosts:
          - host: adguard.k8s.hyde.services
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - secretName: wildcard.hyde.services
            hosts:
              - adguard.k8s.hyde.services
    priorityClassName: keep-alive
    persistence:
      volumeClaimSpec:
        resources:
          requests:
            storage: 1Gi
    bootstrapEnabled: false
