# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app adguard-home
  namespace: *app
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: app-template
      version: 4.1.0
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      adguard-home:
        strategy: Recreate
        containers:
          app:
            image:
              repository: adguard/adguardhome
              tag: v0.107.62
            env:
              TZ: Australia/Melbourne
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /login.html
                    port: &port 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probe
    defaultPodOptions:
      annotations:
        backup.velero.io/backup-volumes: config
      priorityClassName: keep-alive
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
      dns:
        controller: *app
        type: LoadBalancer
        annotations:
          metallb.io/loadBalancerIPs: 192.168.4.17,2404:e80:661b:4::17
        externalTrafficPolicy: Local
        ipFamilyPolicy: PreferDualStack
        ipFamilies:
          - IPv4
          - IPv6
        ports:
          dns-tcp:
            port: 53
            protocol: TCP
          dns-udp:
            port: 53
            protocol: UDP
    ingress:
      app:
        enabled: true
        className: internal-nginx
        hosts:
          - host: &host adguard.k8s.hyde.services
            paths:
              - path: /
                service:
                  identifier: app
                  port: *port
        tls:
          - secretName: wildcard.hyde.services
            hosts:
              - *host
    persistence:
      config:
        globalMounts:
          - path: /opt/adguardhome/work
            subPath: work
          - path: /opt/adguardhome/conf
            subPath: config
        accessMode: ReadWriteOnce
        size: 2Gi
