apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
  namespace: open-webui
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: open-webui
      version: 5.20.0
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: flux-system
  values:
    ollama:
      ollama:
        gpu:
          enabled: true
          type: "nvidia"
          number: 1
          nvidiaResource: "nvidia.com/gpu"
        models:
          pull:
            - deepseek-r1
        #  run:
        #    - llama3
      runtimeClassName: nvidia
      persistentVolume:
        enabled: true
        size: 32Gi
    ingress:
      enabled: true
      ingressClass: external-nginx
      host: chat.hyde.services
      tls: true
      existingSecret: wildcard.hyde.services
    persistence:
      enabled: true
      size: 2Gi
    enableOpenaiApi: false
