apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: authentik
    namespace: authentik
spec:
    interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    chart:
        spec:
            chart: authentik
            version: 2025.2.2
            interval: 5m
            sourceRef:
                kind: HelmRepository
                name: authentik
                namespace: flux-system
    values:
        global:
            deploymentStrategy:
                type: Recreate
        authentik:
            secret_key: ENC[AES256_GCM,data:B5hUuUQKFL3zUwD69NLL+p6IVEYaweNmh4XakTwRgTUxmkocVaGIaGFbzL8w3qxvtgk=,iv:OIlXI8Tjuv5GXGRnMjg/jjZMs3eoSALSsi0StW1XLGE=,tag:xTgE/SnFnrx/yZyQ4WU3LQ==,type:str]
            postgresql:
                host: postgresql.database.svc.cluster.local
                user: authentik
                password: ENC[AES256_GCM,data:BoopI8eH+JItscXXbkY=,iv:Zf2IB/DfPcFl/61WNQt0+A0BIU1Oz4GmXWMhCLtxDu4=,tag:V/1wvCsdS9+PwTFOxjks8Q==,type:str]
            email:
                host: mail.hyde.services
                port: "587"
                username: no-reply@hyde.services
                password: ENC[AES256_GCM,data:d3rNh+xHFeBmGrPY3PCG4Q==,iv:Ia6h8IMDbMSuLkmDFaw9Be8KsCkw6JNsmuY/8I0Pv2M=,tag:Rgegk8kGRcAipywViP+moA==,type:str]
                use_tls: true
                timeout: "30"
                from: no-reply@hyde.services
            redis:
                host: redis-master
        server:
            ingress:
                enabled: true
                ingressClassName: external-nginx
                hosts:
                    - auth.hyde.services
                tls:
                    - secretName: wildcard.hyde.services
                      hosts:
                        - auth.hyde.services
            podAnnotations:
                backup.velero.io/backup-volumes: media
            volumes:
                - name: media
                  persistentVolumeClaim:
                    claimName: authentik-media-pvc
                - name: custom-css
                  configMap:
                    name: authentik-custom-css
            volumeMounts:
                - name: media
                  mountPath: /media
                - name: custom-css
                  mountPath: /web/dist/custom.css
                  subPath: custom.css
        postgresql:
            enabled: false
        geoip:
            enabled: true
            accountId: ENC[AES256_GCM,data:6AB2nBZ5,iv:EnkL6i693nlg7jPW1bzfXxLNJ4XKKemlbeoaV9rDleI=,tag:+cS9Ygg1gKsTxAnKyabpXQ==,type:str]
            licenseKey: ENC[AES256_GCM,data:MLwZJjDrxPmjdrV9X7gKse3t4gcPPCPQccjE1RVUXft0WiXnsU9bhA==,iv:+7h6yRnnnE/qnwVyO0b1UHIidxpDNJENeYNG7Ft24es=,tag:OzWzLX0JWwRdiEKpeGI2Fw==,type:str]
        redis:
            enabled: true
            fullnameOverride: redis
            architecture: standalone
            master:
                persistence:
                    size: 128Mi
                resourcesPreset: nano
            auth:
                enabled: false
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1umudqfh963mmhgkgatylwh9jgez7qh4twpaqy3ea3nlcarhm09hq5er32r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TVBkZkluQ01lNU5Jd3ds
            TE4zNklJVll5YVFHeGVpN29MMUdXL29CckNjCm9qS3J0WUtkK21LZW9lYSt0K21X
            ZzdwQXIwVzVHMnFqMXdnbmp2UlVXVFEKLS0tIFV0eDdTMXl5WEhWcTd5aW4wdGpw
            aDVxSUFNOUY0SWYybE5iK1JSYk95MEUKHOpUIKJJsU09xb5S5QzqEz720GSiLuBw
            jSMQUpn1Kf1nQg87HdSi0ATj3U6fkzkaemCY+yek1OKdKhlAE8KLMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-14T03:37:07Z"
    mac: ENC[AES256_GCM,data:Jm0Viyf86BkJ0uOoVySG4wXh6RW7cA4E25EfDS1FzJ4qcP3rHPBhIEw2ox4aVerSzbQOSxhPuXQ+ynjJ6+bwBX/7Ku3zb780Exkeb1Fo1OErbNxtZvhVRc3OaCwU0mPIJA8nBw1eH7yiHfx/XSO+zPpfr2O2k/4dqwciIEolSxo=,iv:X8kOdljgFauJRArC5x6g933QVFAu0+PkapQyLQVIGzs=,tag:KIJsuFvPw4N4RYXh7RucZQ==,type:str]
    pgp: []
    encrypted_regex: ^(password|secret_key|accountId|licenseKey)$
    version: 3.9.4
