apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - ingress.sops.yaml
  - limit-egress.yaml
  - namespace.yaml
  - pvc.yaml
secretGenerator:
  - name: authentik-values
    files:
      - values.yaml=values.sops.yaml
    options:
      disableNameSuffixHash: true
