apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-media-pvc
  namespace: authentik
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: authentik-dist-pvc
#  namespace: authentik
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Mi
