apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - app/immich # migrated
# - app/plex # migrated
  - app/private
# - app/tautulli # migrated
# - app/wizarr
# - ingress.sops.yaml
  - namespace.yaml
