apiVersion: v1
kind: ConfigMap
metadata:
  name: fs-restore-action-config
  namespace: velero
  labels:
    velero.io/plugin-config: ""
    velero.io/pod-volume-restore: RestoreItemAction
data:
  secCtx: |
    capabilities:
      drop: []
      add: []
    allowPrivilegeEscalation: true
    runAsUser: 0
    runAsGroup: 0
