apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: velero
      version: 9.0.2
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: velero
        namespace: flux-system
  values:
    image:
      repository: velero/velero
      tag: v1.16.0
    upgradeCRDs: true
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.12.0
        volumeMounts:
          - mountPath: /target
            name: plugins
    deployNodeAgent: true
    nodeAgent:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
    credentials:
      existingSecret: cloud-credentials-minio
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
    configuration:
      extraEnvVars:
        TZ: Australia/Melbourne
      backupStorageLocation:
        - name: k8s-homelab
          provider: aws
          default: true
          bucket: velero
          prefix: k8s-homelab
          config:
            region: minio
            s3ForcePathStyle: true
            s3Url: http://192.168.3.6:9000
            checksumAlgorithm: ""
      volumeSnapshotLocation:
        - name: k8s-homelab
          provider: aws
          config:
            region: minio
    metrics:
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
        spec:
          - alert: VeleroBackupPartialFailures
            annotations:
              message: "Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} partial failures."
            expr: |
              velero_backup_partial_failure_total{schedule!=""} / velero_backup_attempt_total{schedule!=""} > 0.25
            for: 15m
            labels:
              severity: warning
          - alert: VeleroBackupFailures
            annotations:
              message: "Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} failed backups."
            expr: |
              velero_backup_failure_total{schedule!=""} / velero_backup_attempt_total{schedule!=""} > 0.25
            for: 15m
            labels:
              severity: critical
