---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: velero
      version: 8.1.0
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: velero
        namespace: flux-system
  values:
    image:
      repository: velero/velero
      tag: v1.15.0
    upgradeCRDs: true
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.11.0
        volumeMounts:
          - mountPath: /target
            name: plugins
    metrics:
      enabled: true
      scrapeInterval: 120s
      scrapeTimeout: 30s
    deployNodeAgent: true
    credentials:
      existingSecret: cloud-credentials-minio
    configuration:
      extraEnvVars:
        TZ: Australia/Melbourne
      backupStorageLocation:
        - name: k8s-homelab
          provider: aws
          default: true
          bucket: velero
          prefix: k8s-homelab
          config:
            region: minio
            s3ForcePathStyle: true
            s3Url: http://192.168.3.6:9000
            checksumAlgorithm: ""

      volumeSnapshotLocation:
        - name: k8s-homelab
          provider: aws
          config:
            region: minio
