apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - namespace.yaml
  - resources/restore-as-root.yaml
  - resources/schedule.yaml
  - secret.sops.yaml
