apiVersion: v1
kind: Secret
metadata:
    name: unpackerr-secrets
    namespace: media-downloaders
data:
    radarrKey: ENC[AES256_GCM,data:Q7Zn3HaXBcjQXsZCHhM3EaZY2NVw/gWDJq+zcsRiQpN58UU+Zjv/ZOCX6Hc=,iv:XMQrokpFO0e/9euYqqV70wQ/22Gq1l4NI5JVE6KB47U=,tag:GBiljT4ZjnBkEf9uNrTweQ==,type:str]
    radarr3dKey: ENC[AES256_GCM,data:gniPPI2kbGtLdEIuxPROs7C6sA7pk4CcIJ1EW/IH2FoOleqB/lHodHpCiog=,iv:aXkodzLfiwjRwmaQaZ8zLSHiVPTaGsnuYEpT4FkBYeI=,tag:9mi3QJQ4EXGxndgxUeLEcw==,type:str]
    sonarrKey: ENC[AES256_GCM,data:hy1ebXcz/WHRc0fKpLj6JH8XjnMfuKGvhA7bnZIZzkd68I7y/WFF+ROx1Y8=,iv:/GXzKqfdN3j6FOnGy+uwaug5ojFl4ms/T+0Zmlft4sA=,tag:n78xi2E/mIkcmOQPnbelZg==,type:str]
    webhookUrl: ENC[AES256_GCM,data:PEiUKfcSZKQmC0Vs4pjga5CQ1o24KzgivhXkSK9+91Tm5P2pqZCBCanHX0MmiZOKTELhamwTrLAqsAjkvrhEh2jIJkf+2e3WNrfxR2BOZIxsJALvVLcgSL7wfG/ygVXv/ie4PtUF4pS+KDCRglqmOCr5/2Xd9MHu,iv:QqIaaA8t/w0ea8oI5EBfmlEEKM4L+l39DIGXmjOXU8c=,tag:orSwBqTUEB2/CSJBY+PlYg==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1umudqfh963mmhgkgatylwh9jgez7qh4twpaqy3ea3nlcarhm09hq5er32r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMFd4UDcvSE1EZHFpdGJv
            cHN0dlZzcHNUN284MHErS0o2TXVBNFlxK2pvCkkzY2V2NHRYT3UxUlpEdGt5N1I2
            V3Evd0R1ZWJselVBc1lOWitxcjZVYWsKLS0tIFM1dkZtWHA3aGtkS05FOGgyMld0
            ZitEalVIL3Nra0Jnck5LR2R5dG1iSW8KnIogk7hX1gmOl+5ITd5H72jzEEO6dDe9
            TiUaJ37MV9zCNbCS6m7mkWDxaxM7qzfZ5FhoS7q8IpfUTRrrn+KSsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-28T11:10:15Z"
    mac: ENC[AES256_GCM,data:kfMd49jj40N5oSpctVou/sn+QCo0IE8+Lf7QvFONj2oS9He8o22umATcyL81efPaD8p4zWQKU4xYn76T8MZRwYtsAGFuUrtKOkfQgx3qOfEHGZbxxjI1sQb5BkLqLmcjVRIEivHvoOy5tv4nfXCNNKZ9mjS8ArNlLnOsAjV2rVU=,iv:7kBOyP9JgtNRGKNNXxDhyHj4Gjr5ikoo3jV7+JDsr2I=,tag:c/LJ5RqxCnCb7iC0LSUA8A==,type:str]
    encrypted_regex: ^(data|stringData|annotations|)$
    version: 3.10.2
