apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sabnzbd
  namespace: {{ $.Release.Namespace }}
spec:
  ingressClassName: internal-nginx
  tls:
    - hosts:
        - "*.k8s.hyde.services"
      secretName: wildcard.hyde.services
  rules:
    - host: sabnzbd.k8s.hyde.services
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: sabnzbd
                port:
                  number: {{ .Values.sabnzbd.port }}
